### ISSUE TITLE
Code release plan

### ISSUE THREAD

**Issue by zhezh** [karfly/learnable-triangulation-pytorch#1]
Hi, I am interested at your learnable triangulation work, is there a plan about when will you release the code?
Thanks~!

**Comment by yurymalkov** [comment]
Hi @zhezh,
We are undergoing internal procedures for publishing and, simultaneously, cleaning up the code. 
ETA is 1-2 months.

**Comment by Kaahan** [comment]
Hi! Is there any update on the release date for the code? A few of the implementation details were a bit vague in the paper, so a reference would be much appreciated!

Thanks

**Comment by karfly** [comment]
Hello, everybody.
We're planning to release code by the end of September.
