### ISSUE TITLE
Viewing data in 3D space

### ISSUE THREAD

**Issue by jamalknight** [karfly/learnable-triangulation-pytorch#102]
Hi there

Assuming the data in ` /logs/eval_h36m_vol../checkpoints/0000/results.pkl` file are the coordinates of the predicted pose - how can I view this data (joint positions) in a 3D application, in 3D space?

They look like they are in arrays of numbers, I would like to convert them to x,y,z coordinates so that they can be viewed in 3d space.

Any help on the matter would be great, thanks.

**Comment by shrubb** [comment]
See #51
