### ISSUE TITLE
GPU utility during training

### ISSUE THREAD

**Issue by ky66111** [karfly/learnable-triangulation-pytorch#103]
Thank you for the elegant work and easy-read code.
I have 2 questions when training on my own data. 
1. The GPU utility always runs below 20% during training on my own data. I wonder if `torch.svd` processes on CPU and becomes the bottleneck. Can you tell more details about GPU utility info when training on hm36? And is `torch.svd` only implement CPU version?
2. How to training on multiple GPU, is it OK to just transfer the code to official `DataParallelModel` and `DataParallelCriterion` ?

**Comment by shrubb** [comment]
Hi.

1. No, I'm sure it's on GPU, we checked that.
2. Yes, should be so.

**Comment by ky66111** [comment]
Thank you for the reply. I'll check for other reasons why my GPU utility is very low.
