### ISSUE TITLE
Training/evaluating on all sequential frames

### ISSUE THREAD

**Issue by jamalknight** [karfly/learnable-triangulation-pytorch#104]
This model skips redundant frames (where the subject is not moving) and therefore does not process all frames. If I wanted to test a sequence of all frames (not skipping any) could I: 

1) use this model trained on skipped frames (as it currently is) and evaluate it on a sequence where no frames are skipped

or

2) would I have to retrain using data that does not skip frames?

Ultimately I would like to have smooth sequential motion without frames skipped and wondering what the best approach would be.

Thanks

**Comment by shrubb** [comment]
No, you don't have to retrain. The model will work already. It doesn't "skip redundant frames", it's just that the dataset was preprocessed this way. That doesn't matter.

**Comment by jamalknight** [comment]
Great, thanks
