### ISSUE TITLE
Will CMU Panoptic dataset be added ?

### ISSUE THREAD

**Issue by cagcag** [karfly/learnable-triangulation-pytorch#105]
Sorry to bother, I wonder whether the CMU Panoptic dataset will be added.

**Comment by Samleo8** [comment]
I'm not sure what's the main author's progress on the CMU dataset, but I have done some work on it (#75 #76 #79 etc) and you can view some of the work in my repo [here](https://github.com/Samleo8/learnable-triangulation-pytorch).

**Comment by karfly** [comment]
There're no plans for the near future to add CMU Panoptic dataset.
