### ISSUE TITLE
Undistorting all frames available

### ISSUE THREAD

**Issue by jamalknight** [karfly/learnable-triangulation-pytorch#106]
I would like to undistort all frames (without skipping any) using the steps in 

`https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m_preprocessing/README.md`

I have processed the data in H36M so that I have all distorted frames available, but running `undistort-h36m.py` I am getting skipped frames - 1,8,11,13 ..etc (image attached). 

Could you please point out where in the code I would have to adjust to create undistorted frames for all available?
I would like to eval all sequential frames in the eval set instead of skipping any.

![undistort_skipped](https://user-images.githubusercontent.com/38970401/90465094-fd825880-e151-11ea-8c2d-4cadd47ddde8.png)

**Comment by jamalknight** [comment]
Resolved:
The steps 4-6 [here](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m_preprocessing/README.md) need to be re run on the dataset where all frames are processed

**Comment by anas-zafar** [comment]
@jamalknight can you please share the processed dataset if possible
