### ISSUE TITLE
Trained models for volumetric and algebraic 

### ISSUE THREAD

**Issue by lyshuga** [karfly/learnable-triangulation-pytorch#11]
Hello, I was wondering if there are any available trained models on Human3.6M dataset. I would appreciate if you share these ones for public access.

Kindly,
Mykola

**Comment by dulibubai** [comment]
Can you help me with the dataset Human3.6M? Thanks a lot!

**Comment by dulibubai** [comment]
> Hello, I was wondering if there are any available trained models on Human3.6M dataset. I would appreciate if you share these ones for public access.
> 
> Kindly,
> Mykola



> Thanks in advance, looking forward to seeing them.

Do you have the Human3.6M dataset? Thanks a lot!

**Comment by karfly** [comment]
Added pretrained models.
