### ISSUE TITLE
Question about Human3.6M preprocessing scripts

### ISSUE THREAD

**Issue by Vegetebird** [karfly/learnable-triangulation-pytorch#114]
When I run the python3 generate-labels-npy-multiview.py, why I can't get the warning saying "camera 54138969 isn't present in S11/Directions-2". 
And in your paper said, "some scenes of the ’S9’ validation actor (parts of ’Greeting’, ’SittingDown’ and ’Waiting’", so in "Human3.6M preprocessing scripts", these data are been ignored?

**Comment by shrubb** [comment]
Sorry for the late reply.

> why I can't get the warning saying "camera 54138969 isn't present in S11/Directions-2"

What we see is:

```bash
$ ls datasets/Human3.6M/processed/S11/Directions-2/imageSequence/
55011271/ 58860488/ 60457274/
```

and there's no `54138969` folder. The dataset just doesn't have it (other actions have this folder). Check yours. If the warning didn't fire, it means the folder is there. Even if so, I'm sure it's empty. It's still fine.

> so in "Human3.6M preprocessing scripts", these data are been ignored?

No, they are preprocessed too. You choose to ignore them later, [here](https://github.com/karfly/learnable-triangulation-pytorch/blob/9d1a26ea893a513bdff55f30ecbfd2ca8217bf5d/mvn/datasets/human36m.py#L28).

**Comment by Vegetebird** [comment]
Thank you for your reply! It seems I have the 54138969 folder and it's not empty.....

![image](https://user-images.githubusercontent.com/35993705/97303519-74944580-1895-11eb-80e4-17cb831995d1.png)

**Comment by shrubb** [comment]
Strange. Then I suggest that you manually check some images against the respective frames from other cameras, and you should be OK.

**Comment by anas-zafar** [comment]
@Vegetebird can you please share the Human3.6m dataset. I am unable to access it
