### ISSUE TITLE
How can i generate confidence scores?

### ISSUE THREAD

**Issue by rhljajodia** [karfly/learnable-triangulation-pytorch#115]
Hello.
I am running validation using the volumetric model but noticed that the confidence scores are not being generated. How may i go about doing this?
I tried to change line 229 in mvn/models/triangulation.py to `True` but then, during the state_dict_load (train.py line 412) i get the error:
RuntimeError: Error(s) in loading state_dict for VolumetricTriangulationNet:
	Missing key(s) in state_dict: "backbone.vol_confidences.features.0.weight", "backbone.vol_confidences.features.0.bias", "backbone.vol_confidences.features.1.weight", "backbone.vol_confidences.features.1.bias", "backbone.vol_confidences.features.1.running_mean", "backbone.vol_confidences.features.1.running_var", "backbone.vol_confidences.features.4.weight", "backbone.vol_confidences.features.4.bias", "backbone.vol_confidences.features.5.weight", "backbone.vol_confidences.features.5.bias", "backbone.vol_confidences.features.5.running_mean", "backbone.vol_confidences.features.5.running_var", "backbone.vol_confidences.head.0.weight", "backbone.vol_confidences.head.0.bias", "backbone.vol_confidences.head.2.weight", "backbone.vol_confidences.head.2.bias", "backbone.vol_confidences.head.4.weight", "backbone.vol_confidences.head.4.bias". 
python-BaseException

Please help me out.
Thank you.

**Comment by karfly** [comment]
Hi, @rhljajodia.
Can you share a full command, how you run the validation?
