### ISSUE TITLE
Have some questions

### ISSUE THREAD

**Issue by pervin0527** [karfly/learnable-triangulation-pytorch#135]
Hi. i saw about human36m_batch_128.pkl.

but i don't understand some points.

1. when i read pkl file, ['images'] shape are (128, 4, 384, 384, 3). what is mean about 4?? num of cameras??

2. ['detections'] shapes are (128, 4, 5). thoese bbox coordinates in second?? or third?? if in second, what does mean about 5?

3. the last key of dict, ['indexes']. what is this mean?? files index number?? Why is this necessary?

code:

    import pickle
    import numpy as np
    
    with open('./learnable-triangulation-pytorch/data/human36m_batch_128.pkl', 'rb') as f:
        data = pickle.load(f)
    # print(type(data))
    key_list = list(data.keys())
    # print(key_list)
    # ['images', 'detections', 'cameras', 'keypoints_3d', 'indexes']
    
    images = np.array(data['images'])
    print("IMAGE_SHAPE : ", images.shape)
    
    detections = np.array(data['detections'])
    print("BOUNDING_BOX : ", detections.shape)
    
    cameras = np.array(data['cameras'])
    print("CAMERA_CALIBRATION : ", cameras.shape)
    
    keypoints_3d = np.array(data['keypoints_3d'])
    print("JOINTS_COORDINATES : ", keypoints_3d.shape)
    
    indexes = np.array(data['indexes'])
    print(indexes.shape)

outputs:

    IMAGE_SHAPE :  (128, 4, 384, 384, 3)
    BOUNDING_BOX :  (128, 4, 5)
    CAMERA_CALIBRATION :  (4, 128)
    JOINTS_COORDINATES :  (128, 17, 4)
    (128,)

**Comment by shrubb** [comment]
Hi,

> 4?? num of cameras??
Yes.

> or third??
Yes. 5 is four coordinates plus detection confidence (like in any object detector; range is 0.0 to 1.0; you likely won't need it).

> ['indexes']. what is this mean?? files index number??
Index of sample in dataset (e.g. `Human36MMultiViewDataset`). [Like so](https://github.com/karfly/learnable-triangulation-pytorch/blob/9d1a26ea893a513bdff55f30ecbfd2ca8217bf5d/mvn/datasets/human36m.py#L183). I don't remember why we needed it, probably just for debugging or visualization, or maybe for proper alignment with ground truth.

**Comment by pervin0527** [comment]
@shrubb

I really appreciate to answering the question. thank you.

Because I couldn't get the human 3.6 data set, so currently working on training your model on a custom dataset I have.
