### ISSUE TITLE
Any visualisation scripts will be provided?

### ISSUE THREAD

**Issue by NoLookDefense** [karfly/learnable-triangulation-pytorch#139]
Hello. Will you provide some visualisation scripts for your algorithm like 
https://github.com/yihui-he/epipolar-transformers/blob/master/assets/h36m_vis.png
or
https://www.youtube.com/watch?v=CbTUC7kOk9o
?

**Comment by shrubb** [comment]
Hi, I don't think so. All we are left with (sadly) is this repository.

**Comment by NoLookDefense** [comment]
So sad. Thank you for your reply. Wish you all the best
