### ISSUE TITLE
undistort-h36m

### ISSUE THREAD

**Issue by samvaf** [karfly/learnable-triangulation-pytorch#14]
Hello,

I have done all the steps to preprocess the Human3.6M dataset. However, when I run the script undistort-h36m, I face this problem:

`Dataset length: 527599
Computing distorted meshgrids
  0%|                                                                                                                                                                                   | 0/527599 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "undistort-h36m.py", line 47, in <module>
    sample = dataset[sample_idx]
  File "/media/saman/storage_device/ubuntu/learnable-triangulation/mvn/datasets/human36m_preprocessing/../../../mvn/datasets/human36m.py", line 182, in __getitem__
    if self.keypoints_3d_pred is not None:
AttributeError: 'Human36MMultiViewDataset' object has no attribute 'keypoints_3d_pred'`

**Comment by shrubb** [comment]
Hi @samvaf, this should have been fixed in #13, can you `git pull` and try again?

**Comment by samvaf** [comment]
Hi @shrubb, Thanks a lot. It worked!
