### ISSUE TITLE
Not find the file---experiments/human36m/eval/

### ISSUE THREAD

**Issue by dulibubai** [karfly/learnable-triangulation-pytorch#15]
Hi! I am not find the file :experiments/human36m/eval/  (eval/),can you help me with updating the file?

**Comment by karfly** [comment]
Hello, I’ll add it with pretrained models by the end of the week.

**Comment by dulibubai** [comment]
Thanks a lot !
Can you help me with the Human3.6m dataset? I have log the account in the official network with my teacher's school email,but it needs manual verification from the admins,it will cost long times.
So can you help me with the dataset? It's very significant for me.I'll appreciate it if you can help me.
Looking forward to your reply!(I'm a postgraduate in China,majoring in computer vison.)

**Comment by karfly** [comment]
Yeah, sometimes it takes a long time to get approval from Human3.6M admins. Unfortunately, I can’t share my credentials due to legal issues. I recommend to write email (or emails) to Human3.6M admins to accelerate the process.

**Comment by dulibubai** [comment]
okay! Thanks again.
