### ISSUE TITLE
About human36m-multiview-labels-GTbboxes.npy

### ISSUE THREAD

**Issue by anymyb** [karfly/learnable-triangulation-pytorch#150]
@karfly  Can you provide the file “human36m-multiview-labels-gtbboxes.npy”？  Thank you very much！

**Comment by shrubb** [comment]
Hi, see step 6 [here](https://github.com/karfly/learnable-triangulation-pytorch/blob/9d1a26ea893a513bdff55f30ecbfd2ca8217bf5d/mvn/datasets/human36m_preprocessing/README.md).

**Comment by five1wheel** [comment]
it doesn't work
