### ISSUE TITLE
Can I access Google Cloud for download h36m.zip?

### ISSUE THREAD

**Issue by qbxlvnf11** [karfly/learnable-triangulation-pytorch#152]
Thanks for your research contribution and publishing code!

I will be inferencing Learnable-Triangulation model with baseline model

Would you give me the access authority of your Google Cloud for download h36m.zip?

Email is qbxlvnf11@gmail.com!

**Comment by karfly** [comment]
Hi!
I've just updated urls in all READMEs. Now links are valid.
