### ISSUE TITLE
CMU pretrained weights

### ISSUE THREAD

**Issue by SimicCh** [karfly/learnable-triangulation-pytorch#158]
Hi, great approach for human pose estimation!
I would like to evaluate on CMU dataset. Unfortunately the download link form #83 for CMU pre-trained model weights seems to be down.
Could you upload your pre-trained weights again?
Thank you.

**Comment by shrubb** [comment]
@karfly, is it possible to reupload it to yandex disk like the H36M weights?

**Comment by SimicCh** [comment]
Hi @karfly, @shrubb I hope you could help me. I would like to use your pretrained CMU model for comparison. Would it be possible to reactivate the upload link or create a new one?
Thanks in advance!

**Comment by karfly** [comment]
Hello @SimicCh!
Unfortunately, we are unable to share the CMU weights (see [Data section](https://github.com/karfly/learnable-triangulation-pytorch#data) of the README).

**Comment by anas-zafar** [comment]
Hi @SimicCh were you able to get the cmu pretrained weights? Thanks
