### ISSUE TITLE
Testing in the wild

### ISSUE THREAD

**Issue by edrdos101** [karfly/learnable-triangulation-pytorch#16]
Hello thanks for sharing your awesome work. Could you advice if your code can be adopted to testing on images in the wild and whether at inference it actually requires any information about world position of cameras or camera parameters?

From the first look it doesn't seem so but I want to try out trained models on some of my own images but wanted to make sure I prepare the data correctly

Thanks!

**Comment by karfly** [comment]
Hello!

Our methods are supposed to work with images, captured with a multi-camera setup like Human3.6m. During testing it requires both 1) images and 2) camera setup parameters (extrinsics, intrinsics). So you can run our methods if have both ingredients.

You can look at how Human3.6M and CMU Panoptic datasets were collected and try to build a similar multi-camera setup. Then you should calibrate it and after this, you can run our methods.

**Comment by yurymalkov** [comment]
@schmidje 
The camera parameters are provided within a dataset class, e.g. https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m.py#L145 

You can use the parameters of your setup. 

The learnable part of the algorithm itself does not have access to camera parameters, they are used only to lift the 2D feature maps into the volume. 
We've checked it on a model trained on CMU by applying it to the Human3.6M dataset without any additional training. The results seem to be good: https://youtu.be/z3f3aPSuhqg?t=156

**Comment by shrubb** [comment]
Hi @schmidje, thanks for your interest!

Indeed, your guess isn't quite correct. The intrinsics and extrinsics are not learned, but they are actually passed "as parameters" during inference. And yes, the trained models are reasonably transferable, which means that one can use different camera setups for training and inference. We verified this in the paper by training a network on CMU Panoptic and then testing it on Human3.6M.

As to "where and how should we provide intrinsics and extrinsics parameters", other contributors can provide more detail on that, but basically you should see how a dataset like mvn/datasets/human36m.py is organized and follow its interface. You'll have to provide the same necessary tensors that `__getitem__` yields.

**Comment by moshanATucsd** [comment]
Hi, thanks so much for the great work. I am wondering whether a minimal example could be provided for a few images, without the need for the entire datasets?

**Comment by ZhiRuoo** [comment]
hi, I am trying to evaluate this for some sample pics shot in our lab using a android cell phone camera. 

1. what camera params should I use ? 
2. is there a simplified Test script (python) example, that I can use to run this? instead of having to run a complete eval on a much larger data set etc. 

any quick help would be greatly appreciated. thanks

**Comment by karfly** [comment]
@moshanATucsd @ZhiRuoo

Minimal viable example is a good idea, thank you. I’ll add such example as soon as come back to work from business trip (~3 weeks).

For now you can extract one batch from Human3.6M dataset and see what input data the models require. It’s pretty straightforward, but if you’ll have questions – ask them here.

**Comment by TonyFaith** [comment]
@karfly  would you please tell me how can i  extract one batch human3.6m dataset (Minimal viable example ?)

**Comment by TonyFaith** [comment]
@karfly  sorry karfly, i have not got human3.6m datasets yet (i have applied for that one year ago!). 
 It will be greatly appreciated if you can give some simplified script or Minimal viable example. thanks a lot!

**Comment by junhao1999** [comment]
> @karfly sorry karfly, i have not got human3.6m datasets yet (i have applied for that one year ago!).
> It will be greatly appreciated if you can give some simplified script or Minimal viable example. thanks a lot!

+1

**Comment by karfly** [comment]
@edrdos101 @schmidje @moshanATucsd @junhao1999,
I dumped 1 big batch of Human3.6M, outputted right from dataloader [here](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/train.py#L177). You can download it from [Google Drive](https://drive.google.com/file/d/1f7QT9OvkWXwKB24EC-8wzTpA_VwCsbsm/view?usp=sharing).

Example of usage:
```python3
import pickle

with open("human36m_batch_128.pkl", 'rb) as fin:
    batch = pickle.load(fin)

...  # continue from line https://github.com/karfly/learnable-triangulation-pytorch/blob/master/train.py#L186
```
