### ISSUE TITLE
Please provide example of input

### ISSUE THREAD

**Issue by exotikh3** [karfly/learnable-triangulation-pytorch#22]
Could you please provide example of input for model to be able to reproduce results. I requested access to Human3.6M but I think it would take a lot of time to receive approve.

**Comment by karfly** [comment]
@exotikh3

Hello!
Unfortunately, right now I’m on the business trip and don’t have access to the workstation where data is stored. I’ll provide a minimal viable example as soon as I come back to work.

**Comment by karfly** [comment]
@exotikh3 @junhao1999,
I dumped 1 big batch of Human3.6M, outputted right from dataloader [here](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/train.py#L177). You can download it from [Google Drive](https://drive.google.com/file/d/1f7QT9OvkWXwKB24EC-8wzTpA_VwCsbsm/view?usp=sharing).

Example of usage:
```python3
import pickle

with open("human36m_batch_128.pkl", 'rb) as fin:
    batch = pickle.load(fin)

...  # continue from line https://github.com/karfly/learnable-triangulation-pytorch/blob/master/train.py#L186
```

**Comment by BingEdison** [comment]
finally can try this awesomeness but I'm stuck at something so easy spending hours trying to get and output from the human3.6m batch provided, seems simple if an easy fix could you tell me what I'm doing wrong? 

running python code:
------------------------------------
import pickle


with open('human36m_batch_128.pkl', 'rb') as fin:
    data = pickle.load(fin)
--------------------------------------------------------

outputs error
ModuleNotFoundError: No module named 'mvn'

**Comment by karfly** [comment]
Hi, @BingEdison. 
Please check step 3 at Human3.6M preprocessing: https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m_preprocessing/README.md

**Comment by BingEdison** [comment]
Howdy Karll! however I do not have access to human3.6m dataset , I've downloaded  the file 'bboxes-Human36M-GT' provided on google drive by you and team, following steps seem to require images and directories from human36m dataset is it still possible to complete instructions on above page you've referenced?

**Comment by karfly** [comment]
@BingEdison you can’t perform evaluation or training using dumped batch, I provided above. I shared it to allow people to explore how input data is organized without having whole Human3.6M dataset.

**Comment by aryan-f** [comment]
> @exotikh3 @junhao1999, I dumped 1 big batch of Human3.6M, outputted right from dataloader [here](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/train.py#L177). You can download it from [Google Drive](https://drive.google.com/file/d/1f7QT9OvkWXwKB24EC-8wzTpA_VwCsbsm/view?usp=sharing).
> 
> Example of usage:
> 
> ```python
> import pickle
> 
> with open("human36m_batch_128.pkl", 'rb) as fin:
>     batch = pickle.load(fin)
> 
> ...  # continue from line https://github.com/karfly/learnable-triangulation-pytorch/blob/master/train.py#L186
> ```

Could you share the batch again? The link doesn't seem to be working.

**Comment by five1wheel** [comment]
I'd like to request one, too
