### ISSUE TITLE
testing on the CMU Panoptic dataset

### ISSUE THREAD

**Issue by mingx9527** [karfly/learnable-triangulation-pytorch#24]
Hi @karfly  
Thanks for your sharing sincerely!  I try test the model on the CMU Panoptic dataset,  get into trouble like the result pic:
![vol1](https://user-images.githubusercontent.com/36255328/68263418-f554a300-0080-11ea-9593-7fdcf6bf1921.png)

- resnet152 pre 2d is ok

- gt 3d project to 2d is ok

- but the pre 3d is bad! all point at center of pic

how can i debug it ???

**Comment by karfly** [comment]
Hi, @mingx9527!

I would first check these points:
1. Metric system. In Human3.6M everything is in mm, in CMU Panoptic - in cm. So set `cuboid_side: 250.0` and `scale_keypoints_3d: 1.0` in CMU Panoptic config file.
2. Coordinate systems are different. Check X, Y, Z in Human3.6M and CMU Panoptic.
3. Is estimation of the base point correct?
4. Are camera parameters passed to the model correctly?

**Comment by mingx9527** [comment]
@karfly 
Thank for your help
I will continue to explore according to your instructions also looking forward to your update CMU Panoptic script!
thanks

**Comment by Samleo8** [comment]
I was able to successfully get the CMU Panoptic Dataset going
