### ISSUE TITLE
How to save detected results of 3D human joint positions in JSON files? and generate them only using your pretrained models without Human3.6M dataset?

### ISSUE THREAD

**Issue by BenoitKAO** [karfly/learnable-triangulation-pytorch#27]
How to save detected results of 3D human joint positions in JSON files?

Could you also please describe some examples of any input of videos/ images to generate results of 3D human joint positions in JSON files only using your pretrained models without Human3.6M dataset? 

Thank you very much.

**Comment by karfly** [comment]
Hi, @BenoitKAO.
[Evaluation process](https://github.com/karfly/learnable-triangulation-pytorch#evaluation) generates `results.pkl` file, containing predicted 3D poses for evaluation dataset. You can find this file in logdir of your experiment. Soon I'll add a minimal viable example without a necessity of having full Human3.6M dataset.
