### ISSUE TITLE
Which GPU did you use during training?

### ISSUE THREAD

**Issue by aki34** [karfly/learnable-triangulation-pytorch#28]
Hello!
Thank you for your awesome code sharing.

Now, I try to train the network of algebraic version with following command.
python train.py --config train/human36m_alg.yaml --logdir ./logs

And I got following RuntimeError.

> Traceback (most recent call last):
>   File "train.py", line 486, in <module>
>     main(args)
>   File "train.py", line 465, in main
>     n_iters_total_train = one_epoch(model, criterion, opt, config, train_dataloader, device, epoch, n_iters_total=n_iters_total_train, is_train=True, master=master, experiment_dir=experiment_dir, writer=writer)
>   File "train.py", line 190, in one_epoch
>     keypoints_3d_pred, keypoints_2d_pred, heatmaps_pred, confidences_pred = model(images_batch, proj_matricies_batch, batch)
>   File "/home/akihiko/anaconda3/envs/LT_MV3Dpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/akihiko/MV3Dpose/learnable-triangulation-pytorch/mvn/models/triangulation.py", line 158, in forward
>     heatmaps, _, alg_confidences, _ = self.backbone(images)
>   File "/home/akihiko/anaconda3/envs/LT_MV3Dpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/akihiko/MV3Dpose/learnable-triangulation-pytorch/mvn/models/pose_resnet.py", line 301, in forward
>     x = self.layer3(x)
>   File "/home/akihiko/anaconda3/envs/LT_MV3Dpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/akihiko/anaconda3/envs/LT_MV3Dpose/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
>     input = module(input)
>   File "/home/akihiko/anaconda3/envs/LT_MV3Dpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/akihiko/MV3Dpose/learnable-triangulation-pytorch/mvn/models/pose_resnet.py", line 79, in forward
>     out = self.bn1(out)
>   File "/home/akihiko/anaconda3/envs/LT_MV3Dpose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/akihiko/anaconda3/envs/LT_MV3Dpose/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 76, in forward
>     exponential_average_factor, self.eps)
>   File "/home/akihiko/anaconda3/envs/LT_MV3Dpose/lib/python3.6/site-packages/torch/nn/functional.py", line 1623, in batch_norm
>     training, momentum, eps, torch.backends.cudnn.enabled
> RuntimeError: CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 10.92 GiB total capacity; 9.54 GiB already allocated; 9.12 MiB free; 39.55 MiB cached)

I'm using GTX1080Ti, which has 11GB VRAM, but it seems that the CUDA is out of memory.
So I'd like to ask you which gpu did you use during training?

**Comment by karfly** [comment]
Hi, @aki34!
I already answered similar question in [this issue](https://github.com/karfly/learnable-triangulation-pytorch/issues/23). Please, check my answer there.

**Comment by aki34** [comment]
Hi,

I didn't notice that.
Thank you.
