### ISSUE TITLE
Question about joints' confidences regression and if only 2 views available

### ISSUE THREAD

**Issue by XinjieInformatik** [karfly/learnable-triangulation-pytorch#31]
Hi @karfly , thanks for sharing your great work! The code is very clear. I'm just curious about 2 questions.
Take AlgebraicTriangulationNet as an example,
1. in GlobalAveragePoolingHead, you regress the confidence score for each 2D joint for 3D triangulation, then implement MSE in 3D joints directly. How can the network learn the confidence score correctly in this kind of self-supervision manner?
2. have you done some experiments under only 2 cameras, don't know if the 3D joints can be also recovered robust or not.

**Comment by karfly** [comment]
Hi, @XinjieInformatik!
1. As you can see [here](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/models/triangulation.py#L188), these confidences are used as weights in triangulation (bigger weight => more impact on output 3D keypoint). So they are learned in self-supervision manner.
2. In the paper we provide results for 2 cameras only for CMU Panoptic dataset (see plot below). Also you can see some 2-camera results in [our video](https://youtu.be/z3f3aPSuhqg?t=118) (link with timecode). I believe our method (especially Volumetric) can successfully work with 2 cameras if they are well-positioned.

![mpjpe_vs_number_of_cameras](https://user-images.githubusercontent.com/7571844/68927228-56bef500-0798-11ea-963d-d400b655ded2.png)

**Comment by XinjieInformatik** [comment]
Hi @karfly , thanks a lot for the clear and detail explanation!
