### ISSUE TITLE
Question for training

### ISSUE THREAD

**Issue by Lijianfang6930** [karfly/learnable-triangulation-pytorch#32]
Dear Dr. Karim Iskakov 

   Thanks for ur reply for my last question.  I am trying to repeat your experiment,  I wonder the hardware of ur experiment, and how much time did you cost for a whole training.
   
    I have trained ur model, but it seems I have met some troubles. After three days training by two GPUs of Tesla P100 (meanwhile, the traning process is nomal), the frequency change of the index  "Volatile GPU-Util" become very high and I do not know what's the reason, I even can not use tensorboard to watch the training process although I can wathch the traning process before.

**Comment by TonyFaith** [comment]
@Lijianfang6930  have you got human3.6m datasets？ would you please share that with me so we can discuss about your problem? (i have applied for the data but there is no reply). thx a lot.

**Comment by karfly** [comment]
Hi, @Lijianfang6930!
Please, can you explain what you mean by saying "I even can not use tensorboard to watch the training process"?

**Comment by Lijianfang6930** [comment]
Hi @karfly I  am a freshman of  3D human pose estimation, I appreciate for ur patient reply, but i still want to know ur running hardware platform and time, so that i can figur out whether there are any problem of my operation. Besides, I am looking forward ur training introduce on CMU datasets.

**Comment by karfly** [comment]
@Lijianfang6930, I provided hardware specs in [this issue](https://github.com/karfly/learnable-triangulation-pytorch/issues/23).
