### ISSUE TITLE
demo code and joint order

### ISSUE THREAD

**Issue by sjtu-cx** [karfly/learnable-triangulation-pytorch#33]
Hello!
    Thanks for your excellent work!
    I am using the algebraic model to make predictions on some human36m datas. Actually I use two videos and the corresponding two cameras' parameters , but the results seem not correct(I prepare data and do preprocessing according to the code in human36m.py). 
    I wonder whether you will provide a demo code  and what is the joint order of the output of the algebraic model?

**Comment by karfly** [comment]
Hi, @sjtu-cx.
Right now only Human3.6M code is available and it can be transferred to your demo task. [Here](https://github.com/karfly/learnable-triangulation-pytorch/issues/24#issuecomment-550197667) I gave some advices on how to transfer current Human3.6M pipeline to CMU Panoptic - it can be useful for you.

To determine the order of the joints you can use this [visualisation code](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/utils/vis.py#L267).

**Comment by sjtu-cx** [comment]
@karfly 
Hi！
I crop the image and resize it to [384,384],and pass it to the model .Then I plot the 2d pose according to your visualisation code, however the result is bad . Here is the result .
![right_resize](https://user-images.githubusercontent.com/30372856/69507190-9c37ab00-0f6c-11ea-9f3b-839107037377.jpg)
![2dpose_right](https://user-images.githubusercontent.com/30372856/69507201-a9549a00-0f6c-11ea-8834-9bfc35189d66.jpg)

**Comment by karfly** [comment]
@sjtu-cx 
There can be many reasons why it happens. Check [this dumped input batch](https://github.com/karfly/learnable-triangulation-pytorch/issues/16#issuecomment-556968608) and compare with your input.

**Comment by sjtu-cx** [comment]
@karfly 
Hi!
I have figured out the problem. I use yolo v3 to detect person in the image and generate bounding box to crop the raw image.
However the bounding box's aspect ratio may be not consistent with the one used in training,  which may result in inaccurate 2d pose results.

**Comment by karfly** [comment]
Hi, @sjtu-cx.
Glad to hear, that you found the problem.

**Comment by TonyFaith** [comment]
@sjtu-cx  hi, do you mean "scale_bbox" parameters for dataset preparation? i used an open bbox detector to get the bbox data, how shall i set my  "scale_bbox"? thanks a lot.

**Comment by sjtu-cx** [comment]
> @sjtu-cx hi, do you mean "scale_bbox" parameters for dataset preparation? i used an open bbox detector to get the bbox data, how shall i set my "scale_bbox"? thanks a lot.

I mean when doing inference on a image, the cropped bounding box scale should match the boundinf box scale in training.

**Comment by TonyFaith** [comment]
@sjtu-cx  i have noticed that. what is bounding box scale in training, where can i find it? thanks.
