### ISSUE TITLE
How to download ground truth bounding boxes? (.mat files)

### ISSUE THREAD

**Issue by BenoitKAO** [karfly/learnable-triangulation-pytorch#35]
In the section 'Human3.6M preprocessing scripts':

2. Additionally, download ground truth bounding boxes and unpack them like so: "<dataset-root>/S1/MySegmentsMat/ground_truth_bb/Phoning 1.58860488.mat".

However, I do not know how to download ground truth bounding boxes. (.mat files)

I found all converters are using Matlab. 

Thank you.

**Comment by shrubb** [comment]
The download links are on the same web page of the Human3.6M website where you download images. Have you searched that one?

**Comment by BenoitKAO** [comment]
Thank you very much for your fast reply.

May I ask which part by section 'Download' of Human3.6m?

=====
 Human3.6M (H36M)


   README FOR INFO ABOUT DATA FORMATS

   VISUALIZATION AND LARGE SCALE PREDICTION SOFTWARE
  Version 1.2
  Version 1.0

   TRAINING DATA

     By subject:
   Subject S1  : 	Videos	Segments	Features	Depth	Scanner	Poses
   Subject S5  : 	Videos	Segments	Features	Depth	Scanner	Poses
   Subject S6  : 	Videos	Segments	Features	Depth	Scanner	Poses
   Subject S7  : 	Videos	Segments	Features	Depth	Scanner	Poses
   Subject S8  : 	Videos	Segments	Features	Depth	Scanner	Poses
   Subject S9  : 	Videos	Segments	Features	Depth	Scanner	Poses
   Subject S11 : 	Videos	Segments	Features	Depth	Scanner	Poses

     By scenario:
   Directions       : 	Videos	Segments	Features	Depth	Poses
   Discussion       : 	Videos	Segments	Features	Depth	Poses
   Eating           : 	Videos	Segments	Features	Depth	Poses
   Greeting         : 	Videos	Segments	Features	Depth	Poses
   Phone Call       : 	Videos	Segments	Features	Depth	Poses
   Posing           : 	Videos	Segments	Features	Depth	Poses
   Purchases        : 	Videos	Segments	Features	Depth	Poses
   Sitting          : 	Videos	Segments	Features	Depth	Poses
   Sitting Down     : 	Videos	Segments	Features	Depth	Poses
   Smoking          : 	Videos	Segments	Features	Depth	Poses
   Taking Photo     : 	Videos	Segments	Features	Depth	Poses
   Waiting          : 	Videos	Segments	Features	Depth	Poses
   Walking          : 	Videos	Segments	Features	Depth	Poses
   Walking Dog      : 	Videos	Segments	Features	Depth	Poses
   Walking Together : 	Videos	Segments	Features	Depth	Poses

   TESTING DATA

     By subject:
   Subject S2  : 	Videos	Segments	Features
   Subject S3  : 	Videos	Segments	Features
   Subject S4  : 	Videos	Segments	Features
   Subject S10 : 	Videos	Segments	Features
   

Mixed Reality Testing

     Videos (7)

     README MIXED REALITY

   

Human80K (H80K)


   README FOR INFO ABOUT DATA FORMATS

   METADATA

   VISUALIZATION SOFTWARE
  Version 1

DATA

RGB	Segments	Poses
   

ECCV18 Challenge

     Train/Val Data

     README Train/Val

     Test Data

     README Submission
=====

**Comment by shrubb** [comment]
It should be "Segments" if I recall correctly (yes, their data layout is often misleading).

**Comment by BenoitKAO** [comment]
Excuse me again, do you have Python codes or GitHub links for downloading all these segments' links?
They are too many links...

**Comment by shrubb** [comment]
> Excuse me again, do you have Python codes or GitHub links for downloading all these segments' links?
> They are too many links from Human3.6m...

No. As I remember, there are only about 7 links.

> And also,
> I found 'features' parts that also have mat files, should I download them as well?

I don't think so.

**Comment by BenoitKAO** [comment]
subjects 1, 5, 6, 7, 8, 9, 11 ==> 7 links?

**Comment by Polaris7777777** [comment]
Hi, Sorry to bother, Could you please share the ground truth bounding boxes, thank you so much!
