### ISSUE TITLE
'undistort-h36m.py' with 'undistort_images=True' gets the error. Follow your instructions, is there something I should download?

### ISSUE THREAD

**Issue by BenoitKAO** [karfly/learnable-triangulation-pytorch#36]
Follow your instructions, is there something I should download?

python3 undistort-h36m.py <dataset-root> human36m-multiview-labels-GTbboxes.npy <number-of-parallel-processes>

'undistort-h36m.py' with 'undistort_images=True' gets the error.

# python3 undistort-h36m.py /.../dataroot human36m-multiview-labels-GTbboxes.npy 20
Dataset length: 161362
Computing distorted meshgrids
  0%|                                                                                        | 0/161362 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "undistort-h36m.py", line 47, in <module>
    sample = dataset[sample_idx]
  File "/../../../mvn/datasets/human36m.py", line 143, in __getitem__
    assert os.path.isfile(image_path), '%s doesn\'t exist' % image_path
AssertionError: /.../dataroot/S1/Directions-1/imageSequence-undistorted/54138969/img_000001.jpg doesn't exist

I think the problem occurs here:
            # load image
            image_path = os.path.join(
                self.h36m_root, subject, action, 'imageSequence' + '-undistorted' * self.undistort_images,
                camera_name, 'img_%06d.jpg' % (frame_idx+1))

Thank you.

**Comment by shrubb** [comment]
You seem to have modified `undistort-h36m.py`. Ideally, you shouldn't. Have you tried running it as-is?

**Comment by BenoitKAO** [comment]
Pull the latest version of your source codes and it works fine now.

Thank you so much!
