### ISSUE TITLE
Which folders or files should be placed to ./data/human36m?

### ISSUE THREAD

**Issue by BenoitKAO** [karfly/learnable-triangulation-pytorch#38]
I am confused about:

2. Place the preprocessed dataset to ./data/human36m.

Which folders or files should be placed to ./data/human36m?

Thank you.

**Comment by karfly** [comment]
@BenoitKAO 
If you followed [this Human3.6M preprocessing guide](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m_preprocessing/README.md), then you used repository [h36m-fetch](https://github.com/anibali/h36m-fetch). Place contents of dir `h36m-fetch` to `./data/human36m`.

You can check paths in [this config](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/experiments/human36m/train/human36m_vol_softmax.yaml) to understand the structure.
