### ISSUE TITLE
camera parameters for wild test 

### ISSUE THREAD

**Issue by TonyFaith** [karfly/learnable-triangulation-pytorch#46]
Thanks for this amazing work and code.
 I want to use this model to evaluate my own datasets. I calibrate the camera parameters, input to the model , but the results is ridiculous. I guess that it is caused by wrong camera parameters, would you please show the human36m's raw camera parameter?

**Comment by shrubb** [comment]
Please follow [the instructions for preparing Human3.6M](https://github.com/karfly/learnable-triangulation-pytorch/tree/master/mvn/datasets/human36m_preprocessing). There, we use the camera parameters published [here](https://github.com/una-dinosauria/3d-pose-baseline/).

**Comment by davidmaeurer** [comment]
@TonyFaith Did you manage to get it to work with your own dataset?
