### ISSUE TITLE
problem about obating 3D coordinates

### ISSUE THREAD

**Issue by qiuzhongwei-USTB** [karfly/learnable-triangulation-pytorch#48]
hi,

I saw the input images of RANSACTriangulationNet, AlgebraicTriangulationNet and VolumetricTriangulationNet are **cropped from origin image according to bounding box.**

For RANSAC Triangulation and Algebraic Triangulation method, the coordinate of 2d keypoints should be in the original image coordinate system. The predicted 2d keypoints by 2d pose backbone model are in bounding box image coordinate system.

But I didn't see where you convert the predicted 2d keypoint into original image coordinate system.

could you help me dispel my confuse?

Thanks

**Comment by karfly** [comment]
Hi, @qiuzhongwei-USTB.

Very good question! Instead of converting points from "bbox" coordinate system back to "original image" coordinate system, we just change camera intrinsics [after crop](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m.py#L152) and [after resize](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m.py#L158).

**Comment by qiuzhongwei-USTB** [comment]
hi,

Thanks for your reply! That's a good method.

In your code, S9/[Greeting-2,SittingDown-2,Waiting-1] are damaged actions.
Could you tell me what's the problem of these videos or their annotations? I didn't find the problems of these videos after I download these data.

**Comment by shrubb** [comment]
@qiuzhongwei-USTB in those scenes, the calibration matrices are wrong. Namely, the whole coordinate system is slightly displaced. View those scenes with [this script](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m_preprocessing/view-dataset.py) to verify.

**Comment by qiuzhongwei-USTB** [comment]
@shrubb Thanks for your reply!

I have checked these damaged data.
As you said, the whole coordinate system is slightly displaced in those scenes.
But the camera matrices are same as all actions. As a result, the reason is that the 3d coordinates annotations of those videos are displaced.

Is that right?

**Comment by shrubb** [comment]
Yes.
