### ISSUE TITLE
pretrained weights on smaller backbones

### ISSUE THREAD

**Issue by sjtu-cx** [karfly/learnable-triangulation-pytorch#49]
Hello!
Have you ever tried to train on smaller backbone networks like resnet18?
If so, could you please provide the pretrained backbone's weights?

**Comment by karfly** [comment]
Hi, @sjtu-cx!
We tried it in our early experiments. Pretrained weights were not saved.

**Comment by sjtu-cx** [comment]
Hi,@karfly 
I tried to change the backbone to resnet18 which is pretrained on MPII , I just change the backbone parameters in config file. 
However the final mpjpe is quite large(almost 1000+).
So I wonder what's the performance in your experiment and do you have any advice to this problem?

**Comment by karfly** [comment]
What kind of model do you use?

**Comment by sjtu-cx** [comment]
> What kind of model do you use?
algebraic model

**Comment by karfly** [comment]
Algebraic model is sensitive to backbone pretraining. I’d try to pretrain it on MPII + Human3.6M as we did in the paper.

**Comment by sjtu-cx** [comment]
Ok,I will try.Thanks!

**Comment by yihui-he** [comment]
Hi, thanks for the excellent work! I’m also trying to pretrain small models. Could you share the code for pretraining on coco+mpii+human3.6m? Thank you!

**Comment by karfly** [comment]
Hi, @yihui-he.
Sorry, but we're not planning to release that code.

**Comment by richardblythman** [comment]
Hey @karfly. On this subject, what was the reason for pretraining on COCO and fine tuning jointly on MPII and H3.6m. For example, why not fine tune jointly on COCO and H3.6m? Or only on H3.6m?
