### ISSUE TITLE
How to get derivatives of w mentioned in algebraic triangulation approach?

### ISSUE THREAD

**Issue by lucas946** [karfly/learnable-triangulation-pytorch#5]
According to equation 4 in your paper, it is straightforward to get the 3D coordinate vector y via differentiable Singular Value Decomposition. But When I can't figure out the derivatives of w  when network training is in the backward-propagation phase. I have a lack of knowledge about matrix derivatives, and can you explain this derivation process in detail?

**Comment by karfly** [comment]
Hey,

We used already implemented differentiable Singular Value Decomposition from PyTorch - [torch.svd](https://pytorch.org/docs/stable/torch.html#torch.svd). Details can be found in the [PyTorch docs](https://pytorch.org/docs/stable/torch.html#torch.svd) or in the source code.

**Comment by lucas946** [comment]
Thanks a lot, I have checked it, it does work.
