### ISSUE TITLE
Visualising the evaluation results 

### ISSUE THREAD

**Issue by Samleo8** [karfly/learnable-triangulation-pytorch#51]
Is there an easy way/tool for us to visualise the evaluation results of the Human3.6M data set, much like how it is done/shown in the video? 

Or would we have to parse the pickle dataset ourselves?

Thank you!

**Comment by karfly** [comment]
Hi, @Samleo8!
All the visualization tools are collected here: https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/utils/vis.py.

**Comment by shrubb** [comment]
Also, maybe you will find the [ground truth annotations viewer](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m_preprocessing/view-dataset.py) useful.

**Comment by Samleo8** [comment]
Is there documentation on how data in the outputted pickle file looks? 
It seems that in order to use the `vis.py` tool I need to know how to unpack the data ?

**Comment by Samleo8** [comment]
Several other questions as I look through the code of `vis.py`:

```
def visualize_batch(images_batch, heatmaps_batch, keypoints_2d_batch, proj_matricies_batch,
                    keypoints_3d_batch_gt, keypoints_3d_batch_pred,
```

It seems `visualize_batch` is the most likely function for use for my purpose?

However, I do not know what to pass in for `images_batch` and `keypoints_3d_batch_gt` since the pickle file does not seem to contain any information.

Moreover, I am unsure if directly passing in the unpickled data from `keypoints_3d_batch_pred` is correct, as it might not be in the correct format required by the function?

Thank you and greatly appreciate your help!

**Comment by karfly** [comment]
@Samleo8, do you mean pickle file from [this issue](https://github.com/karfly/learnable-triangulation-pytorch/issues/22)?

**Comment by Samleo8** [comment]
@karfly No I meant the `results.pkl` file that resulted from running `train.py --eval`

**Comment by Samleo8** [comment]
@karfly @shrubb @Danivilanova

In a sense, the issue is "resolved" because I can visualise the results through tensorboard.

However, because I have no idea how the results are being formatted/the way to parse them, I don't have a way of using the evaluation results for anything meaningful, nor applying it directly to another dataset of my own? Is there a way to resolve this?

Thank you!

**Comment by karfly** [comment]
The structure of the results.pkl file is fully determined by the code. Here (https://github.com/karfly/learnable-triangulation-pytorch/blob/master/train.py#L353) you can find, how we dump the results-dict. The results-dict is filled with data some lines of code above.

**Comment by davidmaeurer** [comment]
I'm sorry, but I still don't quite understand how to use the visualization tool. Do I have to write a separate program that calls these functions? And I have the same question as @Samleo8 regarding the parameters of the visualization function.

**Comment by karfly** [comment]
Hi, @davidmaeurer!
We don't have a standalone visualization tool, so you should write a separate program to visualize your data. In [train.py](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/train.py) you can find example on how to visualize a batch.
