### ISSUE TITLE
Is it possible to use this excellent tool without any training?

### ISSUE THREAD

**Issue by annihi1ation** [karfly/learnable-triangulation-pytorch#52]
Hi, professor!
In my lab, my conductor and I cannot apply for the human3.6m dataset. Whereas we need using your tool to deploy a human pose software. Thus I wonder if we can using your wonderful tool directly on video file without any datasets?
Looking forward to your reply:)

**Comment by karfly** [comment]
Hi, right now there is no such possibility. You need to write some additional code to do it.

**Comment by annihi1ation** [comment]
uhm, thanks all the same 😹

发自我的iPhone


------------------ Original ------------------

**Comment by anas-zafar** [comment]
@annihi1ation were you able to do it? Thanks
