### ISSUE TITLE
CMU Panoptic style annotation

### ISSUE THREAD

**Issue by isarandi** [karfly/learnable-triangulation-pytorch#53]
This work would be very useful for me if there were models available trained on CMU Panoptic. I would like to get CMU-like (so COCO-like) annotations for Human3.6M. I thought of just running the CMU-trained net on H36M, as the video shows very impressive results. If you cannot release the code yet, can you perhaps upload your resulting CMU-like poses for the H36M images?

I'm looking into implementing this myself, by changing stuff from H36M paths and settings to CMU in this repo, but I'm really not sure if I'm looking at a day's worth of work here or two weeks. I'm a bit reluctant to jump straight in, since if it was so easy you probably would have released it already...

**Comment by karfly** [comment]
Hi, @isarandi.
I hope I’ll release CMU pretrained models in two weeks.

**Comment by zzzheng** [comment]
Hi,
I am doing transfer learning on CMU Panoptic. The paper mentions that 

> For the tests we use the 17-subset of the 19-joint annotation format in the dataset, which coincides with the popular COCO format.

However, in the evaluation function, only 6 keypoints were used. Could you please clarify a little bit? Thank you in advance!
```
if transfer_cmu_to_human36m or transfer_human36m_to_human36m:
            human36m_joints = [10, 11, 15, 14, 1, 4]
            if transfer_human36m_to_human36m:
                cmu_joints = [10, 11, 15, 14, 1, 4]
            else:
                cmu_joints = [10, 8, 9, 7, 14, 13]

            keypoints_gt = keypoints_gt[:, human36m_joints]
            keypoints_3d_predicted = keypoints_3d_predicted[:, cmu_joints]
```

**Comment by yurymalkov** [comment]
Hi @zzzheng 
This is for transfer tests between CMU and Human3.6M only (`transfer_cmu_to_human36m or transfer_human36m_to_human36m`). 
COCO and Human3.6M have very different subset of keypoints.

**Comment by zzzheng** [comment]
Thank you!

⁣Get BlueMail for Android ​
