### ISSUE TITLE
Bbox requirements

### ISSUE THREAD

**Issue by Samleo8** [karfly/learnable-triangulation-pytorch#54]
It seems that the BBOXes used for Human3.6M are all squares. 

If we are transferring to other datasets, do we need to ensure that the BBOXes are square, or can they be any size? Also, must the BBOXes for the same person remain the same size from one frame to another?

Thank you!

**Comment by shrubb** [comment]
Hi,

When training, we wanted to be able to (1) stack frames from different cameras into one tensor, and to (2) stack those stacks into minibatches. Both imply having same sizes of cropped images over the dataset. So we chose the size of NxN just by looking at people in the dataset: on average, square crops seemed to be the tightest ones.

If you want to use a model trained on square crops, then ideally you will want, as always, make your test/transfer data resemble training data as closely as possible. This means square crops. Although rectangular crops may work, one then has to tweak the code, changing batches to `for` loops etc.
