### ISSUE TITLE
details of experimental settings on CMU dataset 

### ISSUE THREAD

**Issue by MasakazuYposhimura** [karfly/learnable-triangulation-pytorch#55]
Thank you very much for sharing the great work.
I want to know the detail of the experiment setting for CMU dataset.

In your paper, it is said that 4 cameras was used for validation and I want to know the camera IDs of them.
Also, I can't find how to split videos into train/val in the paper of "Monocular total capture."

Finally, I would appreciate to know how long it takes to train.
Thank you very much.

**Comment by karfly** [comment]
Hi, @MasakazuYposhimura.

Almost all the answers you can find here: https://github.com/karfly/learnable-triangulation-pytorch/issues/19. It takes about 5 days to train.

**Comment by MasakazuYposhimura** [comment]
Hi, @karfly.

I'm sorry to create a new issue and thank you for quick reply.
