### ISSUE TITLE
Regarding the volumetric triangulation, how is the heatmap projected into the Volume

### ISSUE THREAD

**Issue by davidmaeurer** [karfly/learnable-triangulation-pytorch#57]
Hi,
I read your paper, but I don't quite understand how the heatmaps are projected into the Volume. Do you know the exact orientation of each camera and use a transformation matrix, or how does the system project the different views into the same Volume? 
Also you wrote that you tested a network trained on human3.6m on the CMU Panoptic dataset. I presume that he Camera setup in the two datasets is different. So is it possible to use a network trained on human3.6m on other data out of the box, or did you need to enter configure the System for different data?
Best regards,
David

**Comment by karfly** [comment]
Hi, @davidmaeurer.

1. Yes, we assume that the calibrations of the cameras (intrinsics and extrinsics) are known. For the datasets we evaluate our methods on, the calibrations are provided.

2. We didn't test our method to transfer Human3.6M -> CMU Panoptic, but CMU Panoptic -> Human3.6M. We found out that the our models can be successfully transfered. One of the reasons for it is that calibration parameters of the camera setup are **input** data, so the pretrained weights of the models don't explicitly dependent (and overfit) on calibration.

**Comment by davidmaeurer** [comment]
Thanks for your answer. So the camera parameters are used as input for the training process, just alongside the image data? 
So the unprojection into the volume is not directly dependent on the camera parameters? 
Could you tell me at which point in the code the unprojection happens?

**Comment by karfly** [comment]
@davidmaeurer 
Yes, just alongside the image data.
Unprojection is done in this line: https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/models/triangulation.py#L349.

**Comment by davidmaeurer** [comment]
The original ResNet does not use camera parameter data as input. Did you modify it, or does it just get reached through till the 3D part? In which layers is this data actually used? Because I think this data can only be used only in fully connected layers, not in the convolutional part?

**Comment by karfly** [comment]
@davidmaeurer, yes, doesn't use it. Camera parameters used for unprojection just after output of ResNet.
