### ISSUE TITLE
Are you going to use MoVi dataset?

### ISSUE THREAD

**Issue by Ongoza** [karfly/learnable-triangulation-pytorch#58]
MoVi: A Large Multipurpose Motion and Video Dataset
https://arxiv.org/pdf/2003.01888v1.pdf
https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP2/JRHDRN

**Comment by karfly** [comment]
Hi, @Ongoza!
Thank you for the link. Now we're not planning to support this dataset. I think it would be great if the community help with this task
