### ISSUE TITLE
Question about live Cameras

### ISSUE THREAD

**Issue by ahsan3803** [karfly/learnable-triangulation-pytorch#6]
Hi, thanks for your such a nice work. I want to know that this work can be implemented for live cameras instead of images? I want to use 2 live cameras. Is it possible in your work? I read your work but still I'm confused about my problem.

**Comment by karfly** [comment]
Hey,

Yes, it is possible – there is no fundamental limitation of using our approach with live cameras.

But usually live systems requires high FPS (>15) to capture fast movements. At our work we were focused on accuracy, so our models don’t reach real-time speed, but we’re working on it.

**Comment by ahsan3803** [comment]
@karfly Thanks Karim for your reply. Your work is interesting and I'm waiting for the end of September. So I want to know that when you will upload your repository it will included code for camera calibration? or I've to include by myself? If not included then I'll prepare in advance to write the camera calibration code.

**Comment by karfly** [comment]
The won’t include camera calibration toolkit.

**Comment by antithing** [comment]
Hi @lan786 , did you manage to run this code with live camera inputs? Thanks!
