### ISSUE TITLE
Questions about training overfit on human6m dataset

### ISSUE THREAD

**Issue by sunny0212452** [karfly/learnable-triangulation-pytorch#62]
Hi,I used human36m_vol_softmax.yaml to restart training on the human6m dataset (S6, S7, S8). Without using the pre-trained train.pkl, overfitting occurred after 17 epochs. Could you tell me whether the case occur when you train it?

**Comment by karfly** [comment]
Hi, @sunny0212452!
We observed overfitting only after a week of training (>100 epochs).
