### ISSUE TITLE
About training and evaluating in a single view setting when using Volumetric Triangulation

### ISSUE THREAD

**Issue by ShirleyMaxx** [karfly/learnable-triangulation-pytorch#64]
Hi, 
Thanks for your great work!
    
I'm trying to reproduce the 49.9mm in case of a single view setting. Your paper said, "To check the monocular performance we have done a separate experiment with training using a random number of cameras from 1 to 4.". Does this mean that you trained your model with multi-view while evaluating in a single-view? Could you please show me more details about how to train? 
   
 Also, I've set the [config.dataset.train.*] in "human36m_vol_softmax.yaml" like this (batch-size: 4)
![image](https://user-images.githubusercontent.com/19470854/77721008-89210e80-7024-11ea-83ec-30a2ad0306e2.png). 
But when I run the code (I've pre-processed the H36M dataset correctly and same as yours), I got this error,
![image](https://user-images.githubusercontent.com/19470854/77721109-d8ffd580-7024-11ea-8fd7-f1c6222c70ef.png)
where I cannot understand what code line 200-213 in train.py are doing? 
![image](https://user-images.githubusercontent.com/19470854/77721345-896dd980-7025-11ea-9e12-e5ed456e4399.png)

Is it because I trained with a single-view? Could you please help me if you are available?

Thank you! @karfly 

Shirley

**Comment by karfly** [comment]
Hi, @ShirleyMaxx!
1. Yes, to get 49.9 score in single-view setup we train our model on 1 – 4 views simultaneously.
2. In single-view setup we don't predict the global coordinates of the skeleton, we predict coordinates, relative to the base joint (pelvis). Lines 200-213 in train.py do the calculation of the relative positions of the skeleton.

**Comment by ShirleyMaxx** [comment]
> Hi, @ShirleyMaxx!
> 
> 1. Yes, to get 49.9 score in single-view setup we train our model on 1 – 4 views simultaneously.
> 2. In single-view setup we don't predict the global coordinates of the skeleton, we predict coordinates, relative to the base joint (pelvis). Lines 200-213 in train.py do the calculation of the relative positions of the skeleton.

WoW, thanks for your kind and quick reply!!

Now I've figured out what 200-213 lines meant. But I'm still confused about the 'yaml' file you used when you got 49.9 score. 

I mean, when I use this modified 'yaml' to train (batch-size:2, while keeping the other settings same as human36m_vol_softmax.yaml)
![image](https://user-images.githubusercontent.com/19470854/77761350-de840c80-7072-11ea-8721-a6029b959452.png)

 it stuck at Line 208, where you're transforming the coordinates to a relative one, showing that 

> File "train.py", line 208, in one_epoch
> keypoints_3d_gt_transformed[:, torch.arange(n_joints) != base_joint] -= keypoints_3d_gt_transformed[:, base_joint:base_joint + 1]
> IndexError: The shape of the mask [3] at index 0 does not match the shape of the indexed tensor [2, 17, 3] at index 1

So, I'm wondering whether the configuration in my 'yaml' is wrong. Because I've already run successfully with your default configuration (human36m_vol_softmax.yaml), where `randomize_n_views=false`, meaning that it doesn't need to execute the transformation. However, when I set `randomize_n_views=true`, the code stuck at the transformation. So maybe line 208 has something wrong? Or maybe I misunderstand the single-view setting? Thus, could you please show me your config file when getting the 49.9 score?

Thank you sooooo much!!

**Comment by karfly** [comment]
@ShirleyMaxx, yes, the configuration is correct.

**Comment by ShirleyMaxx** [comment]
OK, it's running well now :D Thanks again!! 👍 @karfly
