### ISSUE TITLE
Possible bug in update_after_resize

### ISSUE THREAD

**Issue by ThomasOerkild** [karfly/learnable-triangulation-pytorch#65]
I think there might be a bug in  `Camera.update_after_resize`, or at least it is not very intuitive to use.
`image_shape` must be passed as `(height, width)` while `new_image_shape` must be passed as `(width, height)`

```python
def update_after_resize(self, image_shape, new_image_shape):
    height, width = image_shape
    new_width, new_height = new_image_shape
```

This is not a bug in itself as long as you pass the parameters correctly, but in `VolumetricTriangulationNet` you do

```python
image_shape = tuple(images.shape[3:])
batch_size, n_views, n_joints, heatmap_shape = heatmaps.shape[0], 
                                                  heatmaps.shape[1], 
                                                  heatmaps.shape[2], 
                                                  tuple(heatmaps.shape[3:])

...

new_cameras = deepcopy(batch['cameras'])
for view_i in range(n_views):
    for batch_i in range(batch_size):
        new_cameras[view_i][batch_i].update_after_resize(image_shape, heatmap_shape)
```

Shouldn't it be 
`new_cameras[view_i][batch_i].update_after_resize(image_shape, heatmap_shape[::-1])`
in order to pass the heatmap shape as `(width, height)`?

**Comment by karfly** [comment]
Hi, @ThomasOerkild!
Thank you for opening this issue. It's a bug! Luckily it didn't affect our experiments, because we trained all our networks with square images.
