### ISSUE TITLE
Use of an own data set, taken from 2 equal webcams with different positions

### ISSUE THREAD

**Issue by Gowan1998** [karfly/learnable-triangulation-pytorch#67]
Hi guys,
Thank you very much for this incredible project!!! 
I would like to use my own dataset, which was taken from two equal webcams, from a different perspective. Now I work through the github repo and try to understand everything. Could you give me some information on how I could achieve my goal? Which files should I change, and is this generally possible without changing large parts of the github project.

I am a Ph.D student and work on autonomous driving/deep learning and would like to use your incredible project for my thesis.
Best regards, 
Gowan

**Comment by karfly** [comment]
Hi, @Gowan1998! Thank you!
You need to implement your own Dataset structure for your data. As an example, you can take [our implemention](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m.py) for Human3.6M dataset

**Comment by Gowan1998** [comment]
Thank you Karfly for your quick response!
I am currently working on this file. Is this the only passage that is relevant?

**Comment by shrubb** [comment]
Yes, I think this file is sufficient to get an idea how your dataset should be organized. Anyway, your major pain will likely be synchronizing and calibrating those two web cameras.

**Comment by Gowan1998** [comment]
Yes, you're right! Therefore, I will now begin with the dataset that was recorded by only one camera. You have written in your description that it is also possible to run your framework in a single view (single view method).

**Comment by Gowan1998** [comment]
Hello @karfly @shrubb , 
I read your paper and questioned if I still need the coordinates of the pelvis if I have several cameras ( multi-view ). I asking because of this line: "volumetric triangulation also generalizes to monocular images if human’s approximate position is known". This sounds like it's only necessary if you only use one camera.

**Comment by shrubb** [comment]
This is correct. If you have a multi-camera setup, you can use e.g. algebraic model to locate the pelvis and thus tell the volumetric model where to "place the cube". If you have one camera, you'll have to invent something to make a guess.

**Comment by Gowan1998** [comment]
Okay, this is really interesting. But I'm afraid it's not good for the execution time. Is that so? Furthermore do you have more information about the execution time or fps? 

PS: Many thanks for the quick answers!

**Comment by shrubb** [comment]
We haven't tried live execution. Our aim was to achieve the highest possible accuracy, so the execution time wasn't an issue. However, I believe acceleration is feasible after a bit of rather simple research. It's just a matter of architecture search and probably other small hacks.

Also, #6 might be helpful, someone there tried to do what you want.

**Comment by Gowan1998** [comment]
@shrubb that's right, you have the best accuracy. Can I ask you if you can estimate roughly how many fps in execution the algebraic method would need? Maybe also for RANSAC (your version) and for Volumetric?
Thank you in advance. Of course, I would also make my changes available to you open source.

**Comment by shrubb** [comment]
Sorry, I've got no idea... Maybe @karfly remembers rough numbers, but anyway the easiest and the quickest way is if you measured times yourself on your hardware by running our models with raw weights and with random inputs.

**Comment by polydefk** [comment]
https://github.com/karfly/learnable-triangulation-pytorch/issues/67#issuecomment-615116774 Did you try out in the end? Can you provide roughly some numbers on how many fps each method needs?
