### ISSUE TITLE
Failed to download the h36m.zip while doing the preprocessing (the 5th step)

### ISSUE THREAD

**Issue by DiffenYu** [karfly/learnable-triangulation-pytorch#68]
Thanks for your interesting project.
I want to reproduce the triaing step, but I failed to download the h36m.zip [https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m_preprocessing/README.md](url), the 5th step. Not sure whether you have the same problem when download the data now.

**Comment by shrubb** [comment]
Hi, I just tried and downloaded that file successfully. What is the exact error?

**Comment by DiffenYu** [comment]
> Hi, I just tried and downloaded that file successfully. What is the exact error?
Thanks for your reply.
It shows "Unable to establish SSL connection."
