### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by angechen** [karfly/learnable-triangulation-pytorch#69]
In order to confirm whether the hardware conditions of my laboratory are sufficient, I would like to ask how long does it take to complete the training of the network, how many gpus have been used, and what is the configuration of the GPU.

**Comment by karfly** [comment]
Hi, @angechen!
On a single Nvidia V100 GPU training on Human3.6M takes:
- Algebraic: about a half of week
- Volumetric: about a week

**Comment by angechen** [comment]
Thanks a lot for your answer. I registered on the website of human3.6m, but I haven't received a reply for a long time. Do you know any other ways to get the dataset?

**Comment by karfly** [comment]
You can try to write to the authors of Human3.6M. It might speed up the process.

**Comment by karfly** [comment]
@angechen, I wasn't correct. For training we used  `P40`, not `V100`.
