### ISSUE TITLE
How to interpret human36m-multiview-labels-GTbboxes.npy?

### ISSUE THREAD

**Issue by wwang107** [karfly/learnable-triangulation-pytorch#70]
I want to use my own bounding box for the training. From the way you generate bounding boxes in [generate-labels-npy-multiview.py](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m_preprocessing/generate-labels-npy-multiview.py), it seems like you load your own bonding box from a .json file. Do you mind elaborate on the structure of such .json file, so I can save my own bounding box and use the same script? More specifically, does the .json have structure, the correspondence of bounding box -> subject, action, frame_idx, camera ? 

Thanks in advance!

**Comment by shrubb** [comment]
Hi, sorry for a late answer. Does [this](https://github.com/karfly/learnable-triangulation-pytorch/issues/19#issuecomment-545993330) help?

**Comment by wwang107** [comment]
Yes, it does help! thanks a lot! How do you decide on training and testing images?

**Comment by shrubb** [comment]
You're welcome. See here.

**Comment by shrubb** [comment]
Oops, closed accidentally

**Comment by wwang107** [comment]
Alrighty! thanks for the help. I think I got all I needed for getting your awesome work running.

Again, thanks for the good work and help! you guys are really talented and generous to give help to other researcher or engineer

**Comment by shrubb** [comment]
Cheers!
