### ISSUE TITLE
Pretrained weights file for CMU Dataset

### ISSUE THREAD

**Issue by Samleo8** [karfly/learnable-triangulation-pytorch#72]
I am trying to perform evaluation of the code on the CMU dataset, but am lacking a pretrained weights file (similar to the one at `./data/pretrained/human36m/human36m_alg_10-04-2019/checkpoints/0060/results/train.pkl`) for it. May I know where to find these pretrained weights (they are not on the Google drive given on issue #19 )? Or would I have to train it myself?

Also, do I actually need this pkl file?

_Extra note:_ When I try running my evaluation code, I get this error
```
./data/cmupanoptic/cmu-multiview-labels-MRCNNbboxes.npy has 87981 samples, but './data/pretrained/human36m/human36m_alg_10-04-2019/checkpoints/0060/results/train.pkl' has 159181. Did you follow all preprocessing instructions carefully?
```

_Extra note 2:_ The provided MRCNN Detections on the [Google Drive](https://drive.google.com/drive/folders/1rlFJ-2KWXUapsDpNcFXjJqGDpwOPRh_6) (thank you for them though!) are missing a number of JSON files; not sure if this is an uploading error or because of failed detections

**Comment by Samleo8** [comment]
As an aside, for anybody interesting in using the CMU Dataset for testing and evaluation, feel free to check out and contribute my (WIP) [repository fork](https://github.com/Samleo8/learnable-triangulation-pytorch).

**Comment by anas-zafar** [comment]
Hi @Samleo8 , can you please share where did you get the pretrained weights file (similar to the one at ./data/pretrained/human36m/human36m_alg_10-04-2019/checkpoints/0060/results/train.pkl)? Thanks
