### ISSUE TITLE
Dropbox path not working

### ISSUE THREAD

**Issue by jamalknight** [karfly/learnable-triangulation-pytorch#82]
Step 5 in the: 'Human3.6M pre processing scripts' section there is a link to a dropbox - the files are no longer there. Is there an alternative link to the data?

Step 5:
Existing 3D keypoint positions and camera intrinsics are difficult to decipher, so initially we used the converted ones from Julieta Martinez:

mkdir -p $THIS_REPOSITORY/data/human36m/extra/una-dinosauria-data
cd $THIS_REPOSITORY/data/human36m/extra/una-dinosauria-data
wget **https://www.dropbox.com/s/e35qv3n6zlkouki/h36m.zip**
unzip h36m.zip && rm h36m.zip
cd -_

**Comment by shrubb** [comment]
Hang on, fixing it.

**Comment by jamalknight** [comment]
Thanks, standing by..

**Comment by karfly** [comment]
Hi, @jamalknight!
Fixed it in cec8a0e3978cb5c7bab352d6b8671bcb09bc0dbf.

**Comment by jamalknight** [comment]
Many thanks
