### ISSUE TITLE
Error running collect-bboxes.py

### ISSUE THREAD

**Issue by jamalknight** [karfly/learnable-triangulation-pytorch#86]
I am getting an error in step 4 of the 'Human3.6M Preprocessing Scripts' page

I am not quite sure what the error means:

Command:
python3 collect-bboxes.py ../../../data/human36m/ 14

Result:

S1 Directions-1 54138969
S1 Directions-1 55011271
S1 Directions-1 58860488
S1 Directions-1 60457274
S1 Directions-2 54138969
S1 Directions-2 55011271
S1 Directions-2 58860488
S1 Directions-2 60457274
S1 Discussion-1 54138969
S1 Discussion-1 55011271
S1 Discussion-1 58860488
S1 Discussion-1 60457274
S1 Discussion-2 55011271
S1 Discussion-2 54138969
S1 Discussion-2 58860488
S1 Discussion-2 60457274
S1 Eating-1 54138969
S1 Eating-1 55011271
S1 Eating-1 58860488
S1 Eating-1 60457274
S1 Eating-2 54138969
S1 Eating-2 55011271
S1 Eating-2 58860488
S1 Eating-2 60457274
S1 Greeting-1 54138969
S1 Greeting-1 55011271
S1 Greeting-1 58860488
S1 Greeting-1 60457274
S1 Greeting-2 54138969
S1 Greeting-2 55011271
S1 Greeting-2 58860488
S1 Greeting-2 60457274
S1 Phoning-1 54138969
S1 Phoning-1 55011271
S1 Phoning-1 58860488
S1 Phoning-1 60457274
S1 Phoning-2 54138969
S1 Phoning-2 55011271
S1 Phoning-2 58860488
S1 Phoning-2 60457274
S1 Posing-1 54138969
S1 Posing-1 55011271
S1 Posing-1 58860488
S1 Posing-1 60457274
S1 Posing-2 54138969
S1 Posing-2 55011271
S1 Posing-2 58860488
S1 Posing-2 60457274
S1 Purchases-1 54138969
S1 Purchases-1 55011271
S1 Purchases-1 58860488
S1 Purchases-1 60457274
S1 Purchases-2 54138969
S1 Purchases-2 55011271
S1 Purchases-2 58860488
S1 Purchases-2 60457274
S1 Segments_mat_gt_bb_S1.tgz 54138969
S1 Segments_mat_gt_bb_S1.tgz 55011271
S1 Segments_mat_gt_bb_S1.tgz 58860488
S1 Segments_mat_gt_bb_S1.tgz 60457274
S1 Sitting-1 54138969
S1 Sitting-1 55011271
S1 Sitting-1 58860488
S1 Sitting-1 60457274
S1 Sitting-2 54138969
S1 Sitting-2 55011271
S1 Sitting-2 58860488
S1 Sitting-2 60457274
S1 SittingDown-1 54138969
S1 SittingDown-1 55011271
S1 SittingDown-1 58860488
S1 SittingDown-1 60457274
S1 SittingDown-2 54138969
S1 SittingDown-2 55011271
S1 SittingDown-2 58860488
S1 SittingDown-2 60457274
S1 Smoking-1 54138969
S1 Smoking-1 55011271
S1 Smoking-1 58860488
S1 Smoking-1 60457274
S1 Smoking-2 54138969
S1 Smoking-2 55011271
S1 Smoking-2 58860488
S1 Smoking-2 60457274
S1 TakingPhoto-1 54138969
S1 TakingPhoto-1 55011271
S1 TakingPhoto-1 58860488
S1 TakingPhoto-1 60457274
S1 TakingPhoto-2 54138969
S1 TakingPhoto-2 55011271
S1 TakingPhoto-2 58860488
S1 TakingPhoto-2 60457274
S1 Waiting-1 54138969
S1 Waiting-1 55011271
S1 Waiting-1 58860488
S1 Waiting-1 60457274
S1 Waiting-2 54138969
S1 Waiting-2 55011271
S1 Waiting-2 58860488
S1 Waiting-2 60457274
S1 Walking-1 54138969
S1 Walking-1 55011271
S1 Walking-1 58860488
S1 Walking-1 60457274
S1 Walking-2 54138969
S1 Walking-2 55011271
S1 Walking-2 58860488
S1 Walking-2 60457274
S1 WalkingDog-1 54138969
S1 WalkingDog-1 55011271
S1 WalkingDog-1 58860488
S1 WalkingDog-1 60457274
S1 WalkingDog-2 54138969
S1 WalkingDog-2 55011271
S1 WalkingDog-2 58860488
S1 WalkingDog-2 60457274
S1 WalkingTogether-1 54138969
S1 WalkingTogether-1 55011271
S1 WalkingTogether-1 58860488
S1 WalkingTogether-1 60457274
S1 WalkingTogether-2 54138969
S1 WalkingTogether-2 55011271
S1 WalkingTogether-2 58860488
S1 WalkingTogether-2 60457274
S11 Directions-1 54138969
S11 Directions-1 55011271
S11 Directions-1 58860488
S11 Directions-1 60457274
S11 Directions-2 54138969
S11 Directions-2 55011271
S11 Directions-2 58860488
S11 Directions-2 60457274
S11 Discussion-1 54138969
S11 Discussion-1 55011271
S11 Discussion-1 58860488
S11 Discussion-1 60457274
S11 Discussion-2 54138969
S11 Discussion-2 55011271
S11 Discussion-2 58860488
S11 Discussion-2 60457274
S11 Eating-1 54138969
S11 Eating-1 55011271
S11 Eating-1 58860488
S11 Eating-1 60457274
S11 Eating-2 54138969
S11 Eating-2 55011271
S11 Eating-2 58860488
S11 Eating-2 60457274
S11 Greeting-1 54138969
S11 Greeting-1 55011271
S11 Greeting-1 58860488
S11 Greeting-1 60457274
S11 Greeting-2 54138969
S11 Greeting-2 55011271
S11 Greeting-2 58860488
S11 Greeting-2 60457274
S11 Phoning-1 54138969
S11 Phoning-1 55011271
S11 Phoning-1 58860488
S11 Phoning-1 60457274
S11 Phoning-2 54138969
S11 Phoning-2 55011271
S11 Phoning-2 58860488
S11 Phoning-2 60457274
S11 Posing-1 54138969
S11 Posing-1 55011271
S11 Posing-1 58860488
S11 Posing-1 60457274
S11 Posing-2 54138969
S11 Posing-2 55011271
S11 Posing-2 58860488
S11 Posing-2 60457274
S11 Purchases-1 54138969
S11 Purchases-1 55011271
S11 Purchases-1 58860488
S11 Purchases-1 60457274
S11 Purchases-2 54138969
S11 Purchases-2 55011271
S11 Purchases-2 58860488
S11 Purchases-2 60457274
S11 Segments_mat_gt_bb_S11.tgz 54138969
S11 Segments_mat_gt_bb_S11.tgz 55011271
S11 Segments_mat_gt_bb_S11.tgz 58860488
S11 Segments_mat_gt_bb_S11.tgz 60457274
S11 Sitting-1 54138969
S11 Sitting-1 55011271
S11 Sitting-1 58860488
S11 Sitting-1 60457274
S11 Sitting-2 54138969
S11 Sitting-2 55011271
S11 Sitting-2 58860488
S11 Sitting-2 60457274
S11 SittingDown-1 54138969
S11 SittingDown-1 55011271
S11 SittingDown-1 58860488
S11 SittingDown-1 60457274
S11 SittingDown-2 54138969
S11 SittingDown-2 55011271
S11 SittingDown-2 58860488
S11 SittingDown-2 60457274
S11 Smoking-1 54138969
S11 Smoking-1 55011271
S11 Smoking-1 58860488
S11 Smoking-1 60457274
S11 Smoking-2 54138969
S11 Smoking-2 55011271
S11 Smoking-2 58860488
S11 Smoking-2 60457274
S11 TakingPhoto-1 54138969
S11 TakingPhoto-1 55011271
S11 TakingPhoto-1 58860488
S11 TakingPhoto-1 60457274
S11 TakingPhoto-2 54138969
S11 TakingPhoto-2 55011271
S11 TakingPhoto-2 58860488
S11 TakingPhoto-2 60457274
S11 Waiting-1 54138969
S11 Waiting-1 55011271
S11 Waiting-1 58860488
S11 Waiting-1 60457274
S11 Waiting-2 54138969
S11 Waiting-2 55011271
S11 Waiting-2 58860488
S11 Waiting-2 60457274
S11 Walking-1 54138969
S11 Walking-1 55011271
S11 Walking-1 58860488
S11 Walking-1 60457274
S11 Walking-2 54138969
S11 Walking-2 55011271
S11 Walking-2 58860488
S11 Walking-2 60457274
S11 WalkingDog-1 54138969
S11 WalkingDog-1 55011271
S11 WalkingDog-1 58860488
S11 WalkingDog-1 60457274
S11 WalkingDog-2 54138969
S11 WalkingDog-2 55011271
S11 WalkingDog-2 58860488
S11 WalkingDog-2 60457274
S11 WalkingTogether-1 54138969
S11 WalkingTogether-1 55011271
S11 WalkingTogether-1 58860488
S11 WalkingTogether-1 60457274
S11 WalkingTogether-2 54138969
S11 WalkingTogether-2 55011271
S11 WalkingTogether-2 58860488
S11 WalkingTogether-2 60457274
S5 Directions-1 54138969
S5 Directions-1 55011271
S5 Directions-1 58860488
S5 Directions-1 60457274
S5 Directions-2 54138969
S5 Directions-2 55011271
S5 Directions-2 58860488
S5 Directions-2 60457274
S5 Discussion-1 54138969
S5 Discussion-1 55011271
S5 Discussion-1 58860488
S5 Discussion-1 60457274
S5 Discussion-2 54138969
S5 Discussion-2 55011271
S5 Discussion-2 58860488
S5 Discussion-2 60457274
S5 Eating-1 54138969
S5 Eating-1 55011271
S5 Eating-1 58860488
S5 Eating-1 60457274
S5 Eating-2 54138969
S5 Eating-2 55011271
S5 Eating-2 58860488
S5 Eating-2 60457274
S5 Greeting-1 54138969
S5 Greeting-1 55011271
S5 Greeting-1 58860488
S5 Greeting-1 60457274
S5 Greeting-2 54138969
S5 Greeting-2 55011271
S5 Greeting-2 58860488
S5 Greeting-2 60457274
S5 Phoning-1 54138969
S5 Phoning-1 55011271
S5 Phoning-1 58860488
S5 Phoning-1 60457274
S5 Phoning-2 54138969
S5 Phoning-2 55011271
S5 Phoning-2 58860488
S5 Phoning-2 60457274
S5 Posing-1 54138969
S5 Posing-1 55011271
S5 Posing-1 58860488
S5 Posing-1 60457274
S5 Posing-2 54138969
S5 Posing-2 55011271
S5 Posing-2 58860488
S5 Posing-2 60457274
S5 Purchases-1 54138969
S5 Purchases-1 55011271
S5 Purchases-1 58860488
S5 Purchases-1 60457274
S5 Purchases-2 54138969
S5 Purchases-2 55011271
S5 Purchases-2 58860488
S5 Purchases-2 60457274
S5 Segments_mat_gt_bb_S5.tgz 54138969
S5 Segments_mat_gt_bb_S5.tgz 55011271
S5 Segments_mat_gt_bb_S5.tgz 58860488
S5 Segments_mat_gt_bb_S5.tgz 60457274
S5 Sitting-1 54138969
S5 Sitting-1 55011271
S5 Sitting-1 58860488
S5 Sitting-1 60457274
S5 Sitting-2 54138969
S5 Sitting-2 55011271
S5 Sitting-2 58860488
S5 Sitting-2 60457274
S5 SittingDown-1 54138969
S5 SittingDown-1 55011271
S5 SittingDown-1 58860488
S5 SittingDown-1 60457274
S5 SittingDown-2 54138969
S5 SittingDown-2 55011271
S5 SittingDown-2 58860488
S5 SittingDown-2 60457274
S5 Smoking-1 54138969
S5 Smoking-1 55011271
S5 Smoking-1 58860488
S5 Smoking-1 60457274
S5 Smoking-2 54138969
S5 Smoking-2 55011271
S5 Smoking-2 58860488
S5 Smoking-2 60457274
S5 TakingPhoto-1 54138969
S5 TakingPhoto-1 55011271
S5 TakingPhoto-1 58860488
S5 TakingPhoto-1 60457274
S5 TakingPhoto-2 54138969
S5 TakingPhoto-2 55011271
S5 TakingPhoto-2 58860488
S5 TakingPhoto-2 60457274
S5 Waiting-1 54138969
S5 Waiting-1 55011271
S5 Waiting-1 58860488
S5 Waiting-1 60457274
S5 Waiting-2 54138969
S5 Waiting-2 55011271
S5 Waiting-2 58860488
S5 Waiting-2 60457274
S5 Walking-1 54138969
S5 Walking-1 55011271
S5 Walking-1 58860488
S5 Walking-1 60457274
S5 Walking-2 54138969
S5 Walking-2 55011271
S5 Walking-2 58860488
S5 Walking-2 60457274
S5 WalkingDog-1 54138969
S5 WalkingDog-1 55011271
S5 WalkingDog-1 58860488
S5 WalkingDog-1 60457274
S5 WalkingDog-2 54138969
S5 WalkingDog-2 55011271
S5 WalkingDog-2 58860488
S5 WalkingDog-2 60457274
S5 WalkingTogether-1 54138969
S5 WalkingTogether-1 55011271
S5 WalkingTogether-1 58860488
S5 WalkingTogether-1 60457274
S5 WalkingTogether-2 54138969
S5 WalkingTogether-2 55011271
S5 WalkingTogether-2 58860488
S5 WalkingTogether-2 60457274
S6 Directions-1 54138969
S6 Directions-1 55011271
S6 Directions-1 58860488
S6 Directions-1 60457274
S6 Directions-2 54138969
S6 Directions-2 55011271
S6 Directions-2 58860488
S6 Directions-2 60457274
S6 Discussion-1 54138969
S6 Discussion-1 55011271
S6 Discussion-1 58860488
S6 Discussion-1 60457274
S6 Discussion-2 54138969
S6 Discussion-2 55011271
S6 Discussion-2 58860488
S6 Discussion-2 60457274
S6 Eating-1 54138969
S6 Eating-1 55011271
S6 Eating-1 58860488
S6 Eating-1 60457274
S6 Eating-2 54138969
S6 Eating-2 55011271
S6 Eating-2 58860488
S6 Eating-2 60457274
S6 Greeting-1 54138969
S6 Greeting-1 55011271
S6 Greeting-1 58860488
S6 Greeting-1 60457274
S6 Greeting-2 54138969
S6 Greeting-2 55011271
S6 Greeting-2 58860488
S6 Greeting-2 60457274
S6 Phoning-1 54138969
S6 Phoning-1 55011271
S6 Phoning-1 58860488
S6 Phoning-1 60457274
S6 Phoning-2 54138969
S6 Phoning-2 55011271
S6 Phoning-2 58860488
S6 Phoning-2 60457274
S6 Posing-1 54138969
S6 Posing-1 55011271
S6 Posing-1 58860488
S6 Posing-1 60457274
S6 Posing-2 54138969
S6 Posing-2 55011271
S6 Posing-2 58860488
S6 Posing-2 60457274
S6 Purchases-1 54138969
S6 Purchases-1 55011271
S6 Purchases-1 58860488
S6 Purchases-1 60457274
S6 Purchases-2 54138969
S6 Purchases-2 55011271
S6 Purchases-2 58860488
S6 Purchases-2 60457274
S6 Segments_mat_gt_bb_S6.tgz 54138969
S6 Segments_mat_gt_bb_S6.tgz 55011271
S6 Segments_mat_gt_bb_S6.tgz 58860488
S6 Segments_mat_gt_bb_S6.tgz 60457274
S6 Sitting-1 54138969
S6 Sitting-1 55011271
S6 Sitting-1 58860488
S6 Sitting-1 60457274
S6 Sitting-2 54138969
S6 Sitting-2 55011271
S6 Sitting-2 58860488
S6 Sitting-2 60457274
S6 SittingDown-1 54138969
S6 SittingDown-1 55011271
S6 SittingDown-1 58860488
S6 SittingDown-1 60457274
S6 SittingDown-2 54138969
S6 SittingDown-2 55011271
S6 SittingDown-2 58860488
S6 SittingDown-2 60457274
S6 Smoking-1 54138969
S6 Smoking-1 55011271
S6 Smoking-1 58860488
S6 Smoking-1 60457274
S6 Smoking-2 54138969
S6 Smoking-2 55011271
S6 Smoking-2 58860488
S6 Smoking-2 60457274
S6 TakingPhoto-1 54138969
S6 TakingPhoto-1 55011271
S6 TakingPhoto-1 58860488
S6 TakingPhoto-1 60457274
S6 TakingPhoto-2 54138969
S6 TakingPhoto-2 55011271
S6 TakingPhoto-2 58860488
S6 TakingPhoto-2 60457274
S6 Waiting-1 54138969
S6 Waiting-1 55011271
S6 Waiting-1 58860488
S6 Waiting-1 60457274
S6 Waiting-2 54138969
S6 Waiting-2 55011271
S6 Waiting-2 58860488
S6 Waiting-2 60457274
S6 Walking-1 54138969
S6 Walking-1 55011271
S6 Walking-1 58860488
S6 Walking-1 60457274
S6 Walking-2 54138969
S6 Walking-2 55011271
S6 Walking-2 58860488
S6 Walking-2 60457274
S6 WalkingDog-1 54138969
S6 WalkingDog-1 55011271
S6 WalkingDog-1 58860488
S6 WalkingDog-1 60457274
S6 WalkingDog-2 54138969
S6 WalkingDog-2 55011271
S6 WalkingDog-2 58860488
S6 WalkingDog-2 60457274
S6 WalkingTogether-1 54138969
S6 WalkingTogether-1 55011271
S6 WalkingTogether-1 58860488
S6 WalkingTogether-1 60457274
S6 WalkingTogether-2 54138969
S6 WalkingTogether-2 55011271
S6 WalkingTogether-2 58860488
S6 WalkingTogether-2 60457274
S7 Directions-1 54138969
S7 Directions-1 55011271
S7 Directions-1 58860488
S7 Directions-1 60457274
S7 Directions-2 54138969
S7 Directions-2 55011271
S7 Directions-2 58860488
S7 Directions-2 60457274
S7 Discussion-1 54138969
S7 Discussion-1 55011271
S7 Discussion-1 58860488
S7 Discussion-1 60457274
S7 Discussion-2 54138969
S7 Discussion-2 55011271
S7 Discussion-2 58860488
S7 Discussion-2 60457274
S7 Eating-1 54138969
S7 Eating-1 55011271
S7 Eating-1 58860488
S7 Eating-1 60457274
S7 Eating-2 54138969
S7 Eating-2 55011271
S7 Eating-2 58860488
S7 Eating-2 60457274
S7 Greeting-1 54138969
S7 Greeting-1 55011271
S7 Greeting-1 58860488
S7 Greeting-1 60457274
S7 Greeting-2 54138969
S7 Greeting-2 55011271
S7 Greeting-2 58860488
S7 Greeting-2 60457274
S7 Phoning-1 54138969
S7 Phoning-1 55011271
S7 Phoning-1 58860488
S7 Phoning-1 60457274
S7 Phoning-2 54138969
S7 Phoning-2 55011271
S7 Phoning-2 58860488
S7 Phoning-2 60457274
S7 Posing-1 54138969
S7 Posing-1 55011271
S7 Posing-1 58860488
S7 Posing-1 60457274
S7 Posing-2 54138969
S7 Posing-2 55011271
S7 Posing-2 58860488
S7 Posing-2 60457274
S7 Purchases-1 54138969
S7 Purchases-1 55011271
S7 Purchases-1 58860488
S7 Purchases-1 60457274
S7 Purchases-2 54138969
S7 Purchases-2 55011271
S7 Purchases-2 58860488
S7 Purchases-2 60457274
S7 Segments_mat_gt_bb_S7.tgz 54138969
S7 Segments_mat_gt_bb_S7.tgz 55011271
S7 Segments_mat_gt_bb_S7.tgz 58860488
S7 Segments_mat_gt_bb_S7.tgz 60457274
S7 Sitting-1 54138969
S7 Sitting-1 55011271
S7 Sitting-1 58860488
S7 Sitting-1 60457274
S7 Sitting-2 54138969
S7 Sitting-2 55011271
S7 Sitting-2 58860488
S7 Sitting-2 60457274
S7 SittingDown-1 54138969
S7 SittingDown-1 55011271
S7 SittingDown-1 58860488
S7 SittingDown-1 60457274
S7 SittingDown-2 54138969
S7 SittingDown-2 55011271
S7 SittingDown-2 58860488
S7 SittingDown-2 60457274
S7 Smoking-1 54138969
S7 Smoking-1 55011271
S7 Smoking-1 58860488
S7 Smoking-1 60457274
S7 Smoking-2 54138969
S7 Smoking-2 55011271
S7 Smoking-2 58860488
S7 Smoking-2 60457274
S7 TakingPhoto-1 54138969
S7 TakingPhoto-1 55011271
S7 TakingPhoto-1 58860488
S7 TakingPhoto-1 60457274
S7 TakingPhoto-2 54138969
S7 TakingPhoto-2 55011271
S7 TakingPhoto-2 58860488
S7 TakingPhoto-2 60457274
S7 Waiting-1 54138969
S7 Waiting-1 55011271
S7 Waiting-1 58860488
S7 Waiting-1 60457274
S7 Waiting-2 54138969
S7 Waiting-2 55011271
S7 Waiting-2 58860488
S7 Waiting-2 60457274
S7 Walking-1 54138969
S7 Walking-1 55011271
S7 Walking-1 58860488
S7 Walking-1 60457274
S7 Walking-2 54138969
S7 Walking-2 55011271
S7 Walking-2 58860488
S7 Walking-2 60457274
S7 WalkingDog-1 54138969
S7 WalkingDog-1 55011271
S7 WalkingDog-1 58860488
S7 WalkingDog-1 60457274
S7 WalkingDog-2 54138969
S7 WalkingDog-2 55011271
S7 WalkingDog-2 58860488
S7 WalkingDog-2 60457274
S7 WalkingTogether-1 54138969
S7 WalkingTogether-1 55011271
S7 WalkingTogether-1 58860488
S7 WalkingTogether-1 60457274
S7 WalkingTogether-2 54138969
S7 WalkingTogether-2 55011271
S7 WalkingTogether-2 58860488
S7 WalkingTogether-2 60457274
S8 Directions-1 54138969
S8 Directions-1 55011271
S8 Directions-1 58860488
S8 Directions-1 60457274
S8 Directions-2 54138969
S8 Directions-2 55011271
S8 Directions-2 58860488
S8 Directions-2 60457274
S8 Discussion-1 54138969
S8 Discussion-1 55011271
S8 Discussion-1 58860488
S8 Discussion-1 60457274
S8 Discussion-2 54138969
S8 Discussion-2 55011271
S8 Discussion-2 58860488
S8 Discussion-2 60457274
S8 Eating-1 54138969
S8 Eating-1 55011271
S8 Eating-1 58860488
S8 Eating-1 60457274
S8 Eating-2 54138969
S8 Eating-2 55011271
S8 Eating-2 58860488
S8 Eating-2 60457274
S8 Greeting-1 54138969
S8 Greeting-1 55011271
S8 Greeting-1 58860488
S8 Greeting-1 60457274
S8 Greeting-2 54138969
S8 Greeting-2 55011271
S8 Greeting-2 58860488
S8 Greeting-2 60457274
S8 Phoning-1 54138969
S8 Phoning-1 55011271
S8 Phoning-1 58860488
S8 Phoning-1 60457274
S8 Phoning-2 54138969
S8 Phoning-2 55011271
S8 Phoning-2 58860488
S8 Phoning-2 60457274
S8 Posing-1 54138969
S8 Posing-1 55011271
S8 Posing-1 58860488
S8 Posing-1 60457274
S8 Posing-2 54138969
S8 Posing-2 55011271
S8 Posing-2 58860488
S8 Posing-2 60457274
S8 Purchases-1 54138969
S8 Purchases-1 55011271
S8 Purchases-1 58860488
S8 Purchases-1 60457274
S8 Purchases-2 54138969
S8 Purchases-2 55011271
S8 Purchases-2 58860488
S8 Purchases-2 60457274
S8 Segments_mat_gt_bb_S8.tgz 54138969
S8 Segments_mat_gt_bb_S8.tgz 55011271
S8 Segments_mat_gt_bb_S8.tgz 58860488
S8 Segments_mat_gt_bb_S8.tgz 60457274
S8 Sitting-1 54138969
S8 Sitting-1 55011271
S8 Sitting-1 58860488
S8 Sitting-1 60457274
S8 Sitting-2 54138969
S8 Sitting-2 55011271
S8 Sitting-2 58860488
S8 Sitting-2 60457274
S8 SittingDown-1 54138969
S8 SittingDown-1 55011271
S8 SittingDown-1 58860488
S8 SittingDown-1 60457274
S8 SittingDown-2 54138969
S8 SittingDown-2 55011271
S8 SittingDown-2 58860488
S8 SittingDown-2 60457274
S8 Smoking-1 54138969
S8 Smoking-1 55011271
S8 Smoking-1 58860488
S8 Smoking-1 60457274
S8 Smoking-2 54138969
S8 Smoking-2 55011271
S8 Smoking-2 58860488
S8 Smoking-2 60457274
S8 TakingPhoto-1 54138969
S8 TakingPhoto-1 55011271
S8 TakingPhoto-1 58860488
S8 TakingPhoto-1 60457274
S8 TakingPhoto-2 54138969
S8 TakingPhoto-2 55011271
S8 TakingPhoto-2 58860488
S8 TakingPhoto-2 60457274
S8 Waiting-1 54138969
S8 Waiting-1 55011271
S8 Waiting-1 58860488
S8 Waiting-1 60457274
S8 Waiting-2 54138969
S8 Waiting-2 55011271
S8 Waiting-2 58860488
S8 Waiting-2 60457274
S8 Walking-1 54138969
S8 Walking-1 55011271
S8 Walking-1 58860488
S8 Walking-1 60457274
S8 Walking-2 54138969
S8 Walking-2 55011271
S8 Walking-2 58860488
S8 Walking-2 60457274
S8 WalkingDog-1 54138969
S8 WalkingDog-1 55011271
S8 WalkingDog-1 58860488
S8 WalkingDog-1 60457274
S8 WalkingDog-2 54138969
S8 WalkingDog-2 55011271
S8 WalkingDog-2 58860488
S8 WalkingDog-2 60457274
S8 WalkingTogether-1 54138969
S8 WalkingTogether-1 55011271
S8 WalkingTogether-1 58860488
S8 WalkingTogether-1 60457274
S8 WalkingTogether-2 54138969
S8 WalkingTogether-2 55011271
S8 WalkingTogether-2 58860488
S8 WalkingTogether-2 60457274
S9 Directions-1 54138969
S9 Directions-1 55011271
S9 Directions-1 58860488
S9 Directions-1 60457274
S9 Directions-2 54138969
S9 Directions-2 55011271
S9 Directions-2 58860488
S9 Directions-2 60457274
S9 Discussion-1 54138969
S9 Discussion-1 55011271
S9 Discussion-1 58860488
S9 Discussion-1 60457274
S9 Discussion-2 54138969
S9 Discussion-2 55011271
S9 Discussion-2 58860488
S9 Discussion-2 60457274
S9 Eating-1 54138969
S9 Eating-1 55011271
S9 Eating-1 58860488
S9 Eating-1 60457274
S9 Eating-2 54138969
S9 Eating-2 55011271
S9 Eating-2 58860488
S9 Eating-2 60457274
S9 Greeting-1 54138969
S9 Greeting-1 55011271
S9 Greeting-1 58860488
S9 Greeting-1 60457274
S9 Greeting-2 54138969
S9 Greeting-2 55011271
S9 Greeting-2 58860488
S9 Greeting-2 60457274
S9 Phoning-1 54138969
S9 Phoning-1 55011271
S9 Phoning-1 58860488
S9 Phoning-1 60457274
S9 Phoning-2 54138969
S9 Phoning-2 55011271
S9 Phoning-2 58860488
S9 Phoning-2 60457274
S9 Posing-1 54138969
S9 Posing-1 55011271
S9 Posing-1 58860488
S9 Posing-1 60457274
S9 Posing-2 54138969
S9 Posing-2 55011271
S9 Posing-2 58860488
S9 Posing-2 60457274
S9 Purchases-1 54138969
S9 Purchases-1 55011271
S9 Purchases-1 58860488
S9 Purchases-1 60457274
S9 Purchases-2 54138969
S9 Purchases-2 55011271
S9 Purchases-2 58860488
S9 Purchases-2 60457274
S9 Segments_mat_gt_bb_S9.tgz 54138969
S9 Segments_mat_gt_bb_S9.tgz 55011271
S9 Segments_mat_gt_bb_S9.tgz 58860488
S9 Segments_mat_gt_bb_S9.tgz 60457274
S9 Sitting-1 54138969
S9 Sitting-1 55011271
S9 Sitting-1 58860488
S9 Sitting-1 60457274
S9 Sitting-2 54138969
S9 Sitting-2 55011271
S9 Sitting-2 58860488
S9 Sitting-2 60457274
S9 SittingDown-1 54138969
S9 SittingDown-1 55011271
S9 SittingDown-1 58860488
S9 SittingDown-1 60457274
S9 SittingDown-2 54138969
S9 SittingDown-2 55011271
S9 SittingDown-2 58860488
S9 SittingDown-2 60457274
S9 Smoking-1 54138969
S9 Smoking-1 55011271
S9 Smoking-1 58860488
S9 Smoking-1 60457274
S9 Smoking-2 54138969
S9 Smoking-2 55011271
S9 Smoking-2 58860488
S9 Smoking-2 60457274
S9 TakingPhoto-1 54138969
S9 TakingPhoto-1 55011271
S9 TakingPhoto-1 58860488
S9 TakingPhoto-1 60457274
S9 TakingPhoto-2 54138969
S9 TakingPhoto-2 55011271
S9 TakingPhoto-2 58860488
S9 TakingPhoto-2 60457274
S9 Waiting-1 54138969
S9 Waiting-1 55011271
S9 Waiting-1 58860488
S9 Waiting-1 60457274
S9 Waiting-2 54138969
S9 Waiting-2 55011271
S9 Waiting-2 58860488
S9 Waiting-2 60457274
S9 Walking-1 54138969
S9 Walking-1 55011271
S9 Walking-1 58860488
S9 Walking-1 60457274
S9 Walking-2 54138969
S9 Walking-2 55011271
S9 Walking-2 58860488
S9 Walking-2 60457274
S9 WalkingDog-1 54138969
S9 WalkingDog-1 55011271
S9 WalkingDog-1 58860488
S9 WalkingDog-1 60457274
S9 WalkingDog-2 54138969
S9 WalkingDog-2 55011271
S9 WalkingDog-2 58860488
S9 WalkingDog-2 60457274
S9 WalkingTogether-1 54138969
S9 WalkingTogether-1 55011271
S9 WalkingTogether-1 58860488
S9 WalkingTogether-1 60457274
S9 WalkingTogether-2 54138969
S9 WalkingTogether-2 55011271
S9 WalkingTogether-2 58860488
S9 WalkingTogether-2 60457274
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "collect-bboxes.py", line 59, in load_bboxes
    with h5py.File(bboxes_path, 'r') as h5file:
  File "/home/jamal/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/jamal/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../../../data/human36m/processed/S1/MySegmentsMat/ground_truth_bb/Segments_mat_gt_bb_S1.tgz.54138969.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "collect-bboxes.py", line 71, in load_bboxes
    raise Exception(str(ex) + '; %s %s %s' % (subject, action, camera))
Exception: Unable to open file (unable to open file: name = '../../../data/human36m/processed/S1/MySegmentsMat/ground_truth_bb/Segments_mat_gt_bb_S1.tgz.54138969.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0); S1 Segments_mat_gt_bb_S1.tgz 54138969
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "collect-bboxes.py", line 108, in <module>
    async_result.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
Exception: Unable to open file (unable to open file: name = '../../../data/human36m/processed/S1/MySegmentsMat/ground_truth_bb/Segments_mat_gt_bb_S1.tgz.54138969.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0); S1 Segments_mat_gt_bb_S1.tgz 54138969

**Comment by shrubb** [comment]
Hi. You should delete .tgz or move them somewhere else.

**Comment by jamalknight** [comment]
Thanks, deleting the original .tgz files worked.
