### ISSUE TITLE
When fill retval['cameras'], why do transpose with T in camera params?

### ISSUE THREAD

**Issue by dulibubai** [karfly/learnable-triangulation-pytorch#93]
@karfly Hi!
In  mvn\datasets\human36m_preprocessing\generate-labels-npy-multiview.py
what's the function of the following code:
       camera_retval['R'] = np.array(camera_params['R']).T
       camera_retval['t'] = -camera_retval['R'] @ camera_params['T']
Look forward to your reply?

**Comment by shrubb** [comment]
In this repository, we stick to the OpenCV camera projection convention. In Human3.6M, they used a slightly different convention, so in these lines we are converting the given matrices to make OpenCV formulae work on them.

**Comment by dulibubai** [comment]
Thanks very much ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Egor&amp;nbsp;Burkov&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月14日(星期二) 中午1:30
收件人:&nbsp;&quot;karfly/learnable-triangulation-pytorch&quot;<learnable-triangulation-pytorch@noreply.github.com&gt;;
抄送:&nbsp;&quot;dulibubai&quot;<1257618212@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [karfly/learnable-triangulation-pytorch] When fill retval[&#39;cameras&#39;], why do transpose with T in camera params? (#93)
