### ISSUE TITLE
How does the number of camera views influence the performance on Human 3.6m dataset?

### ISSUE THREAD

**Issue by huagl** [karfly/learnable-triangulation-pytorch#95]
Hi~ This repo and the methods that you proposed in your paper are very impressive! I wonder what's the performance when different number of camera views is used. May you report the experimental results?

**Comment by pablovela5620** [comment]
In the CMU dataset section of the paper they had this chart showing performance of both the ransac and volumetric with the number of cameras 
![image](https://user-images.githubusercontent.com/25287427/88071625-10e5d800-cb42-11ea-8f61-61cac3005ad4.png)

**Comment by karfly** [comment]
@huagl, on Human3.6M you can only measure performance for 2, 3 or 4 camera views.

**Comment by huagl** [comment]
> @huagl, on Human3.6M you can only measure performance for 2, 3 or 4 camera views.

 @karfly Yes, I know. I have a little problem to implement your codes on my machine, for the reason of the space of GPU. How about the performance when only using 2 or 3 camera views to train the network?  Could you report your results when using different number of camera views on Human 3.6M?  Thanks a lot.

**Comment by karfly** [comment]
@huagl, sorry, now I'm working on a different project, so I won't be able to calculate results for 2-, 3-view setup.

**Comment by huagl** [comment]
> @huagl, sorry, now I'm working on a different project, so I won't be able to calculate results for 2-, 3-view setup.

@karfly That's all right. I will keep this issue open to see if anyone could help me. Thanks~
