### ISSUE TITLE
Can it run in realtime?

### ISSUE THREAD

**Issue by dandevs** [karfly/learnable-triangulation-pytorch#97]
I'd very much like to know if this can be used in realtime with a reasonable framerate.

**Comment by siehlema** [comment]
I achieved a batch time of about 120ms on a batch with size 1, an image size of [384,384] and on a host using a 1080Ti.

**Comment by shrubb** [comment]
Since we focused on maximum accuracy, current models aren't directly designed for realtime execution. However, it's definitely possible to have a good speedup with just a bit of research (pick a smaller backbone and/or ligthen the V2V part, then retrain).

**Comment by anas-zafar** [comment]
@dandevs were you able to run it in real time? If yes, could you please guide me how to do so. Thanks
