### ISSUE TITLE
Camera information

### ISSUE THREAD

**Issue by jamalknight** [karfly/learnable-triangulation-pytorch#99]
Hi there

Where can I find the RGB cameras information for the H36M dataset?

ie.
Brand and model
Sensor size
Resolution (width x height in pixels)
Focal lengths
Heights from ground
Angles to ground
Any other info, like distance to other cameras and size of the room, to recreate in 3D.

Thanks

**Comment by shrubb** [comment]
http://vision.imar.ro/human3.6m/
https://github.com/karfly/human36m-camera-parameters

**Comment by jamalknight** [comment]
thanks
